### ISSUE TITLE
uninstall target should maybe only be generated if installed?

### ISSUE THREAD

**Issue by d3x0r** [libressl/portable#1004]
https://github.com/libressl/portable/blob/master/CMakeLists.txt#L530-L543

I would think that `if(NOT TARGET uninstall)` section should be included in the block above it `if(ENABLE_LIBRESSL_INSTALL)`  such that if there is no install, then no uninstall should be generated?

**Comment by d3x0r** [comment]
Here's a visual of generated projects - at the end is 'uninstall' which comes from libressl.

![image](https://github.com/libressl/portable/assets/1909610/1a2aa036-6ce2-44dd-bbd2-654b033a86c9)

The option to skip install is on, because I'm just linking against the static libraries that are built, so there's no install to do, therefore there should also be nothing to uninstall...

**Comment by botovq** [comment]
I see. As I mentioned, I'm happy to merge a PR that does this.

**Comment by botovq** [comment]
This is solved by the merge of #1043, right?

**Comment by d3x0r** [comment]
yes
