### ISSUE TITLE
Build fail : missing RC4 git HEAD

### ISSUE THREAD

**Issue by gene-git** [libressl/portable#1036]
Archlinux git head commit c4afef67c4f82bebc5d06276baea0d87c272f1b1

Clean build started failing with:

/usr/bin/ld: /tmp/cc19rRyX.ltrans7.ltrans.o: in function `rc4_init_key.lto_priv.0':
... portable/apps/ocspcheck/../../crypto/evp/e_rc4.c:131:(.text+0x4e64): undefined reference to `RC4_set_key'

/usr/bin/ld: /tmp/cc19rRyX.ltrans7.ltrans.o: in function `rc4_cipher.lto_priv.0':
... portable/apps/ocspcheck/../../crypto/evp/e_rc4.c:139:(.text+0x4e97): undefined reference to `RC4'

**Comment by gene-git** [comment]
Thank you! Confirm all good.

**Comment by botovq** [comment]
Cool. Thanks!
