### ISSUE TITLE
Unsupported platforms should fail earlier in the configuration process

### ISSUE THREAD

**Issue by CodingMarkus** [libressl/portable#1055]
When trying to cross-compile, e.g. to web assembly, and I configure like 

```
emconfigure ./configure --host=wasm32-unknown-emscripten 
```

and then try to build it using

```
emmake make
```

The compilation fails with

```
  CC       libcrypto_la-cpt_err.lo
In file included from cpt_err.c:58:
In file included from /usr/local/include/openssl/opensslconf.h:15:
/usr/local/include/openssl/macros.h:147:4: error: "OPENSSL_API_COMPAT expresses an impossible API compatibility level"
  147 | #  error "OPENSSL_API_COMPAT expresses an impossible API compatibility level"
      |    ^
1 error generated.
```

But why on earth would the code even read a header file from the OpenSSL/LibreSSL library I currently have installed?  I am trying to build this stuff right now. My system should not even be required to have OpenSSL/LibreSSL installed, otherwise it creates a chicken-egg problem. IMHO, the source code should never reference any OpenSSL/LibreSSL header files in my current system or build environment, only from the source directory of the code I'm trying to build.

It even makes less sense since I'm cross compiling, so my locally installed headers must be totally irrelevant as my local system is not the target system the code will be running on.

If I remove that file, the build fails as well

```
/Library/Automount/Internal/Xcode/App/Xcode_15.3.app/Contents/Developer/usr/bin/make  all-am
  CC       libcrypto_la-cpt_err.lo
cpt_err.c:58:10: fatal error: 'openssl/opensslconf.h' file not found
   58 | #include <openssl/opensslconf.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
```

so you cannot cross-build LibreSSL unless you have either LibreSSL or OpenSSL installed on your build system?

**Comment by CodingMarkus** [comment]
Okay, the problem is caused by `include/openssl/Makefile.am.tpl`. If the architecture is unknown or not explicitly handled, no `opensslconf.h` file is generated at all.

```
opensslconf.h: Makefile
	-echo "generating opensslconf.h ..."
if HOST_AARCH64
	-cp $(top_srcdir)/include/arch/aarch64/opensslconf.h opensslconf.h
endif
if HOST_ARM
	-cp $(top_srcdir)/include/arch/arm/opensslconf.h opensslconf.h
endif
if HOST_I386
	-cp $(top_srcdir)/include/arch/i386/opensslconf.h opensslconf.h
endif
if HOST_MIPS
	-cp $(top_srcdir)/include/arch/mips/opensslconf.h opensslconf.h
endif
if HOST_MIPS64
	-cp $(top_srcdir)/include/arch/mips64/opensslconf.h opensslconf.h
endif
if HOST_POWERPC
	-cp $(top_srcdir)/include/arch/powerpc/opensslconf.h opensslconf.h
endif
if HOST_POWERPC64
	-cp $(top_srcdir)/include/arch/powerpc64/opensslconf.h opensslconf.h
endif
if HOST_RISCV64
	-cp $(top_srcdir)/include/arch/riscv64/opensslconf.h opensslconf.h
endif
if HOST_SPARC64
	-cp $(top_srcdir)/include/arch/sparc64/opensslconf.h opensslconf.h
endif
if HOST_X86_64
	-cp $(top_srcdir)/include/arch/amd64/opensslconf.h opensslconf.h
endif
```

Not handling it is the worst case of handling it! As a bare minimum I would have expected automake to fail or `./configure` to fail (unknown/unsupported architecture), or just use the generic `$(top_srcdir)/include/arch/sh/opensslconf.h` as a fallback, which should always work, and just issue a warning.

Silently doing nothing and then sending the build into a limbo state, where any `opensslconf.h` installed on the system may be used, despite having nothing to do with the current build, seems to totally violate the project goals of creating a more robust code base and a more robust build process, as this certainly has already caused subtle bugs in the past and could even have security implications if the wrong header file is used for making a build.

**Comment by busterb** [comment]
You're porting the code to a new platform, expect you'll need to fix a couple of things. It's not as big a deal as you're making it out to be.

**Comment by CodingMarkus** [comment]
This problem is not about the support of a new platform, but about the fact that if you build code that has to be explicitly adapted to the respective platform and no such adaptation is available for the current platform, this code should fail with an explicit error such as "Unsupported platform" or "Missing platform header". A build process should never just do anything, it should always be deterministic and in such a case also fail deterministically and also explain exactly what the problem was, why it failed.

And if a build system dynamically creates headers or includes them in the build process (as in the case of `opensslconf.h`) and the dynamic header was not created and is not located where the build system expects it, then the build should also fail deterministically and not simply risk that a header with the same name, which is located somewhere in the system and has nothing to do with the current build, is included in the build. Even on a supported platform, this file could end up not being where it should be due to some error in the build scripts and then you build an extremely security-relevant library with a header that the build process has pulled from God knows where?

As for the basic support of wasm/asm.js, that's a different issue, I'm working on it separately, and have almost finished the patch for `configure/make` at least. But this patch would have been possible in 2-3 hours if the build system had behaved sensibly and comprehensibly. As it is, the patch took me 4 days because I first had to figure out what the build system expected to happen, but never checked if it happened and if it actually didn't, just did some complete nonsense that only failed as it eventually ran into compiler errors, yet that is not guaranteed to happen either.

Compared to this, the much-criticized OpenSSL build system behaved in an exemplary manner. The build didn't work right away either, but it failed where it was expected to and it also delivered meaningful errors that immediately showed what had to happen for the build to work. A project that criticizes the OpenSSL build system because it is proprietary and supposedly far too complex should not come up with a build system where you have to guess what the problem is and which simply does whatever in unknown situations because it never checks for these situations and has no meaningful standard behavior or precondition error handling. It might work better with `cmake` or `ninja`, I don't know anything about those build systems, but for most people building code means `./configure && make'.

**Comment by busterb** [comment]
Sure, adjusted the build to fail sooner. Hope this helps!
