### ISSUE TITLE
libressl 4.0.0 build fails when using Clang on Windows

### ISSUE THREAD

**Issue by Tyranisaur** [libressl/portable#1111]
```
  REDACTED\build\clang-cl-ninja-debug\_deps\libressl-src\crypto\compat\posix_win.c(294,5): error : conflicting types for 'libressl_gettimeofday'
    294 | int gettimeofday(struct timeval * tp, struct timezone * tzp)
        |     ^
  REDACTED\build\clang-cl-ninja-debug\_deps\libressl-src\include\compat\sys\time.h(13,22): note: expanded from macro 'gettimeofday'
     13 | #define gettimeofday libressl_gettimeofday
        |                      ^
  REDACTED\build\clang-cl-ninja-debug\_deps\libressl-src\include\compat\sys\time.h(20,5): note: previous declaration is here
     20 | int gettimeofday(struct timeval *tp, void *tzp);
        |     ^
  REDACTED\build\clang-cl-ninja-debug\_deps\libressl-src\include\compat\sys\time.h(13,22): note: expanded from macro 'gettimeofday'
     13 | #define gettimeofday libressl_gettimeofday
        |                      ^
  1 error generated.
```

If I understand this correctly, this build issue surfaced as a result of #1078 because `posix_win.c` now includes `sys/time.h`, resulting in the compiler now seeing both the declaration and definition of the `gettimeofday` function, which have different argument types: `void *` vs `struct timezone *`.  So now the compiler can finally complain about this.

However, the msvc compiler has no issues with this, and doesn't even have a warning that could be emitted for it.

**Comment by botovq** [comment]
There are too many ways to build things on Windows... :)

Yes, it will be a consequence of #1078. For -stable we probably need to stick with `void *`, although I wonder if we can't use `struct timezone *` both in declaration and definition.

**Comment by Tyranisaur** [comment]
> Could you check if #1112 fixes this on your end? I don't have access to Windows, and obviously CI doesn't cover this case.
This seems to work on my end with both msvc and clang.

**Comment by botovq** [comment]
Awesome. Thanks for the report and testing.
