### ISSUE TITLE
curl with OpenSSL quic is missing OSSL_QUIC_client_method()

### ISSUE THREAD

**Issue by orbea** [libressl/portable#1114]
OS: `Gentoo`
LibreSSL: `4.0.0`
curl: `8.10.1`

In Gentoo they want to use the OpenSSL quic implementation for curl by default, but it fails.
```
configure: error: --with-openssl-quic requires quic support and OpenSSL >= 3.3.0
```
In the config.log it shows the failure where the version check is easy to handle, but LibreSSL doesn't have the required `OSSL_QUIC_client_method()` function. Is it possible a future version could add this function? Or is there another way to address this?
```
configure:17538: checking for QUIC support and OpenSSL >= 3.3
configure:17559: x86_64-pc-linux-musl-gcc -o conftest -O2 -pipe -Werror=implicit-function-declaration -Werror=implicit-int -Werror-implicit-function-declaration    -Wl,-O1 -Wl,--as-needed -Wl,-z,pack-r
elative-relocs   conftest.c -lssl -lcrypto -lssl -lcrypto -lz  >&5
conftest.c: In function 'main':
conftest.c:62:8: error: #error need at least version 3.3.0
   62 |       #error need at least version 3.3.0
      |        ^~~~~
conftest.c:64:7: error: implicit declaration of function 'OSSL_QUIC_client_method'; did you mean 'SSLv23_client_method'? [-Werror=implicit-function-declaration]
   64 |       OSSL_QUIC_client_method();
      |       ^~~~~~~~~~~~~~~~~~~~~~~
      |       SSLv23_client_method
cc1: some warnings being treated as errors
configure:17559: $? = 1
configure: failed program was:
| /* confdefs.h */
| #define PACKAGE_NAME "curl"
| #define PACKAGE_TARNAME "curl"
| #define PACKAGE_VERSION "-"
| #define PACKAGE_STRING "curl -"
| #define PACKAGE_BUGREPORT "a suitable curl mailing list: https://curl.se/mail/"
| #define PACKAGE_URL ""
| #define HAVE_STDIO_H 1
| #define HAVE_STDLIB_H 1
| #define HAVE_STRING_H 1
| #define HAVE_INTTYPES_H 1
| #define HAVE_STDINT_H 1
| #define HAVE_STRINGS_H 1
| #define HAVE_SYS_STAT_H 1
| #define HAVE_SYS_TYPES_H 1
| #define HAVE_UNISTD_H 1
| #define STDC_HEADERS 1
| #define HAVE_STDATOMIC_H 1
| #define HAVE_ATOMIC 1
| #define PACKAGE "curl"
| #define VERSION "-"
| #define OS "x86_64-pc-linux-musl"
| #define CURL_DISABLE_LDAP 1
| #define CURL_DISABLE_LDAPS 1
| #define CURL_DISABLE_TELNET 1
| #define CURL_DISABLE_SMB 1
| #define CURL_DISABLE_GOPHER 1
| #define HAVE_SYS_TYPES_H 1
| #define HAVE_SYS_TIME_H 1
| #define HAVE_CLOCK_GETTIME_MONOTONIC 1
| #define HAVE_SYS_TYPES_H 1
| #define HAVE_SYS_TIME_H 1
| #define HAVE_CLOCK_GETTIME_MONOTONIC_RAW 1
| #define HAVE_LIBZ 1
| #define USE_IPV6 1
| #define HAVE_SOCKADDR_IN6_SIN6_SCOPE_ID 1
| #define HAVE_WRITABLE_ARGV 1
| #define HAVE_LIBSSL 1
| #define HAVE_OPENSSL_X509_H 1
| #define USE_OPENSSL 1
| #define HAVE_OPENSSL_RSA_H 1
| #define USE_OPENSSL 1
| #define HAVE_OPENSSL_CRYPTO_H 1
| #define USE_OPENSSL 1
| #define HAVE_OPENSSL_PEM_H 1
| #define USE_OPENSSL 1
| #define HAVE_OPENSSL_SSL_H 1
| #define USE_OPENSSL 1
| #define HAVE_OPENSSL_ERR_H 1
| #define USE_OPENSSL 1
| #define HAVE_LIBRESSL 1
| #define HAVE_SSL_SET_QUIC_USE_LEGACY_CODEPOINT 1
| /* end confdefs.h.  */
| 
| 
|       #include <openssl/ssl.h>
| 
| int main (void)
| {
| 
|       #if (OPENSSL_VERSION_NUMBER < 0x30300000L)
|       #error need at least version 3.3.0
|       #endif
|       OSSL_QUIC_client_method();
| 
|  ;
|  return 0;
| }
| 
configure:17568: result: no
```
The configure check currently remains unchanged upstream in curl.

https://github.com/curl/curl/blob/3040971d12dde9bc2509f1c1d01e99b769400805/m4/curl-openssl.m4#L409

**Comment by botovq** [comment]
LibreSSL is not going to support the OpenSSL quic API.

If you want curl with libressl and quic, you need to link against ngtcp2 and nghttp3 and curl should enable it by default using the BoringSSL API, which everyone except OpenSSL has adopted for many years. I don't think `--with-openssl-quic` is appropriate for LibreSSL.

**Comment by orbea** [comment]
That is the current workaround for what Gentoo is trying to force and if you prefer this issue can be closed with that being considered the solution.

However I noticed these two lines in the ChangeLog before I made this issue, perhaps I misunderstood something?

https://github.com/libressl/portable/blob/0082b6f819b194574f4bde1f4301dc3708a759f0/ChangeLog#L168
https://github.com/libressl/portable/blob/0082b6f819b194574f4bde1f4301dc3708a759f0/ChangeLog#L743

**Comment by botovq** [comment]
It's a [very][1] [long][2] [story][3]...

I think LibreSSL's version of the QUIC API  is considered stable by now and is well enough tested. ngtcp2 supports LibreSSL's quic implementation, which OpenBSD has been using with curl for almost two years: https://github.com/openbsd/ports/commit/7c3daa5884eaa2afc4c3635730ae7d3ede2f3d5e.

The official curl for windows builds have been using LibreSSL for about a year and a half: https://github.com/curl/curl-for-win/discussions/44. haproxy and nginx support QUIC for LibreSSL. There have been bugs but nothing out of the ordinary.

https://github.com/libressl/portable/blob/0082b6f819b194574f4bde1f4301dc3708a759f0/ChangeLog#L168

This refers to a bugfix, see #1093

https://github.com/libressl/portable/blob/0082b6f819b194574f4bde1f4301dc3708a759f0/ChangeLog#L743

That's an entry for 3.6.0 when the API had just landed.

[1]: https://daniel.haxx.se/blog/2021/10/25/the-quic-api-openssl-will-not-provide/
[2]: https://daniel.haxx.se/blog/2024/06/10/http-3-in-curl-mid-2024/comment-page-1/
[3]: https://github.com/quictls/quictls

**Comment by orbea** [comment]
Thanks for those links, looking at the Gentoo ebuilds for curl I see they made sure that quic (And http3) is only supported via OpenSSL's API. I changed that now for the Gentoo LibreSSL overlay, but its annoying that its yet another package that has to be sync'd with the Gentoo repo over and over...

I will close this now unless you think there is something else to do here?
