### ISSUE TITLE
openssl/pemerr.h (empty) should be added for openssl compatibility

### ISSUE THREAD

**Issue by debugmenot** [libressl/portable#1131]
Hi. Sometimes, for packages like cpr, presence of openssl/pemerr.h is required. It's enough to add empty .h file for compatibility:

```
/opt/debugmenot/project_3901/build/_deps/cpr-src/cpr/ssl_ctx.cpp:18:10: fatal error: 'openssl/pemerr.h' file not found
#include <openssl/pemerr.h>
```

**Comment by botovq** [comment]
If this is about [this cpr][1], I don't understand why they include `pemerr.h`. They already have `pem.h` in scope, which has always pulled the error codes in. I'm not really keen on adding useless files for the sake of people following the [advice of linters][2] blindly.

[1]: https://github.com/libcpr/cpr/blob/0e6bf152d4d7233b9a6e5cb287458572b5296f0d/cpr/ssl_ctx.cpp#L17-L18
[2]: https://github.com/libcpr/cpr/commit/ce6bde72f1aeaaad2f3e48acc5b418aa9962ad5f
