### ISSUE TITLE
compat implementation of asprintf depends on POSIX/C99  behavior that does not exist in Visual Studio 2013 and earlier

### ISSUE THREAD

**Issue by cryptoknight** [libressl/portable#218]
The Visual Studio CRT does not define asprintf and thus depends on the implementation in crypto/compat/bsd-asprintf.c. This implementation uses the return value of vsnprintf to determine the necessary size of the buffer in the case that it needs to be larger than the initial guess of 128 bytes. Unfortunately, in versions of Visual Studio older than 2015, vsnprintf always returns -1 if the input count is too small, causing asprintf to fail for any strings longer than 128 bytes.

This can cause an exit() from OPENSSL_config() when LibreSSL is installed to a deep-ish directory and OPENSSLDIR is close to or longer than 128 bytes.

https://msdn.microsoft.com/en-us/library/1kt27hek(v=vs.120).aspx

**Comment by 4a6f656c** [comment]
@busterb do we want to do something here, or is this case of "here's a nickel kid, please get a modern compiler"?

**Comment by busterb** [comment]
I have projects that still need 2013 for other reasons (they do linker tricks that later compilers don't support). Wonder if we couldn't just not rely on Windows vsnprintf at all and include our own as well.

**Comment by bob-beck** [comment]
Might make a lot more sense to try that

**Comment by mikeumbra** [comment]
FYI _snprintf does what you want if you pass NULL/0 for buf/len. The docs don't say if vsnprintf does the same but it's possible that it does.

> [If buffer is a null pointer and count is zero, len is returned as the count of characters required to format the output, not including the terminating null. To make a successful call with the same argument and locale parameters, allocate a buffer holding at least len + 1 characters.](https://msdn.microsoft.com/en-us/library/2ts7cx93(v=vs.120).aspx)
