### ISSUE TITLE
CMake MS Visual C++2017  54-Codeanalysis Warnings

### ISSUE THREAD

**Issue by Dravion** [libressl/portable#315]
The final libs and dlls for arch x86_64-Bit and i386 running just fine, but never the less someone should dig into this soon.

Severity	Code	Description	Project	File	Line	Suppression State
Warning	LNK4221	This object file does not define any previously undefined public symbols, so it will not be used by any link operation that consumes this library	crypto-objects	C:\Users\Dravion\Downloads\libressl-2.5.4.tar\libressl-2.5.4\build\crypto\ecp_nistp521.obj	1	
Warning	C4146	unary minus operator applied to unsigned type, result still unsigned	crypto-objects	C:\Users\Dravion\Downloads\libressl-2.5.4.tar\libressl-2.5.4\crypto\compat\arc4random_uniform.c	41	
Warning	C4295	'sigma': array is too small to include a terminating null character (compiling source file C:\Users\Dravion\Downloads\libressl-2.5.4.tar\libressl-2.5.4\crypto\chacha\chacha.c)	crypto-objects	c:\users\dravion\downloads\libressl-2.5.4.tar\libressl-2.5.4\crypto\chacha\chacha-merged.c	75	
Warning	C4295	'tau': array is too small to include a terminating null character (compiling source file C:\Users\Dravion\Downloads\libressl-2.5.4.tar\libressl-2.5.4\crypto\chacha\chacha.c)	crypto-objects	c:\users\dravion\downloads\libressl-2.5.4.tar\libressl-2.5.4\crypto\chacha\chacha-merged.c	76	
Warning	C4295	'sigma': array is too small to include a terminating null character (compiling source file C:\Users\Dravion\Downloads\libressl-2.5.4.tar\libressl-2.5.4\crypto\compat\arc4random.c)	crypto-objects	c:\users\dravion\downloads\libressl-2.5.4.tar\libressl-2.5.4\crypto\compat\chacha_private.h	51	
Warning	C4295	'tau': array is too small to include a terminating null character (compiling source file C:\Users\Dravion\Downloads\libressl-2.5.4.tar\libressl-2.5.4\crypto\compat\arc4random.c)	crypto-objects	c:\users\dravion\downloads\libressl-2.5.4.tar\libressl-2.5.4\crypto\compat\chacha_private.h	52	
Warning	C4389	'!=': signed/unsigned mismatch	ssl-objects	C:\Users\Dravion\Downloads\libressl-2.5.4.tar\libressl-2.5.4\ssl\d1_pkt.c	560	
Warning	LNK4221	This object file does not define any previously undefined public symbols, so it will not be used by any link operation that consumes this library	crypto-objects	C:\Users\Dravion\Downloads\libressl-2.5.4.tar\libressl-2.5.4\build\crypto\ecp_nistp224.obj	1	
Warning	LNK4221	This object file does not define any previously undefined public symbols, so it will not be used by any link operation that consumes this library	crypto	C:\Users\Dravion\Downloads\libressl-2.5.4.tar\libressl-2.5.4\build\crypto\ecp_nistp224.obj	1	
Warning	LNK4221	This object file does not define any previously undefined public symbols, so it will not be used by any link operation that consumes this library	crypto-objects	C:\Users\Dravion\Downloads\libressl-2.5.4.tar\libressl-2.5.4\build\crypto\ecp_nistp256.obj	1	
Warning	LNK4221	This object file does not define any previously undefined public symbols, so it will not be used by any link operation that consumes this library	crypto	C:\Users\Dravion\Downloads\libressl-2.5.4.tar\libressl-2.5.4\build\crypto\ecp_nistp256.obj	1	
Warning	LNK4221	This object file does not define any previously undefined public symbols, so it will not be used by any link operation that consumes this library	crypto	C:\Users\Dravion\Downloads\libressl-2.5.4.tar\libressl-2.5.4\build\crypto\ecp_nistp521.obj	1	
Warning	C4090	'function': different 'const' qualifiers	crypto-objects	C:\Users\Dravion\Downloads\libressl-2.5.4.tar\libressl-2.5.4\crypto\objects\o_names.c	310	
Warning	C4702	unreachable code	crypto-objects	c:\users\dravion\downloads\libressl-2.5.4.tar\libressl-2.5.4\crypto\x509v3\pcy_tree.c	471	
Warning	C4702	unreachable code	crypto-objects	c:\users\dravion\downloads\libressl-2.5.4.tar\libressl-2.5.4\crypto\pkcs7\pk7_doit.c	663	
Warning	C4701	potentially uninitialized local variable 'buf_outlen' used	openssl	c:\users\dravion\downloads\libressl-2.5.4.tar\libressl-2.5.4\apps\openssl\pkeyutl.c	305	
Warning	C4389	'==': signed/unsigned mismatch	openssl	C:\Users\Dravion\Downloads\libressl-2.5.4.tar\libressl-2.5.4\apps\openssl\compat\poll_win.c	98	
Warning	C4204	nonstandard extension used: non-constant aggregate initializer	openssl	C:\Users\Dravion\Downloads\libressl-2.5.4.tar\libressl-2.5.4\apps\openssl\compat\poll_win.c	256	
Warning	C4115	'timezone': named type definition in parentheses	crypto-objects	C:\Users\Dravion\Downloads\libressl-2.5.4.tar\libressl-2.5.4\crypto\compat\posix_win.c	212	
Warning	C4307	'*': integral constant overflow	crypto-objects	C:\Users\Dravion\Downloads\libressl-2.5.4.tar\libressl-2.5.4\crypto\rc4\rc4_enc.c	162	
Warning	C4307	'*': integral constant overflow	crypto-objects	C:\Users\Dravion\Downloads\libressl-2.5.4.tar\libressl-2.5.4\crypto\rc4\rc4_enc.c	163	
Warning	C4307	'*': integral constant overflow	crypto-objects	C:\Users\Dravion\Downloads\libressl-2.5.4.tar\libressl-2.5.4\crypto\rc4\rc4_enc.c	164	
Warning	C4307	'*': integral constant overflow	crypto-objects	C:\Users\Dravion\Downloads\libressl-2.5.4.tar\libressl-2.5.4\crypto\rc4\rc4_enc.c	165	
Warning	C4206	nonstandard extension used: translation unit is empty	openssl	C:\Users\Dravion\Downloads\libressl-2.5.4.tar\libressl-2.5.4\apps\openssl\speed.c	2157	
Warning	C4701	potentially uninitialized local variable 'data_len' used	ssl-objects	c:\users\dravion\downloads\libressl-2.5.4.tar\libressl-2.5.4\ssl\ssl_asn1.c	209	
Warning	C4245	'initializing': conversion from 'long' to 'unsigned long', signed/unsigned mismatch	ssl-objects	C:\Users\Dravion\Downloads\libressl-2.5.4.tar\libressl-2.5.4\ssl\ssl_ciph.c	212	
Warning	C4245	'initializing': conversion from 'long' to 'unsigned long', signed/unsigned mismatch	ssl-objects	C:\Users\Dravion\Downloads\libressl-2.5.4.tar\libressl-2.5.4\ssl\ssl_ciph.c	227	
Warning	C4245	'initializing': conversion from 'long' to 'unsigned long', signed/unsigned mismatch	ssl-objects	C:\Users\Dravion\Downloads\libressl-2.5.4.tar\libressl-2.5.4\ssl\ssl_ciph.c	300	
Warning	C4245	'initializing': conversion from 'long' to 'unsigned long', signed/unsigned mismatch	ssl-objects	C:\Users\Dravion\Downloads\libressl-2.5.4.tar\libressl-2.5.4\ssl\ssl_ciph.c	305	
Warning	C4245	'initializing': conversion from 'long' to 'unsigned long', signed/unsigned mismatch	ssl-objects	C:\Users\Dravion\Downloads\libressl-2.5.4.tar\libressl-2.5.4\ssl\ssl_ciph.c	310	
Warning	C4245	'initializing': conversion from 'long' to 'unsigned long', signed/unsigned mismatch	ssl-objects	C:\Users\Dravion\Downloads\libressl-2.5.4.tar\libressl-2.5.4\ssl\ssl_ciph.c	315	
Warning	C4389	'!=': signed/unsigned mismatch	ssl-objects	C:\Users\Dravion\Downloads\libressl-2.5.4.tar\libressl-2.5.4\ssl\ssl_clnt.c	940	
Warning	C4146	unary minus operator applied to unsigned type, result still unsigned	ssl-objects	C:\Users\Dravion\Downloads\libressl-2.5.4.tar\libressl-2.5.4\ssl\ssl_pkt.c	167	
Warning	C4018	'<': signed/unsigned mismatch	ssl-objects	C:\Users\Dravion\Downloads\libressl-2.5.4.tar\libressl-2.5.4\ssl\ssl_pkt.c	294	
Warning	C4018	'>=': signed/unsigned mismatch	ssl-objects	C:\Users\Dravion\Downloads\libressl-2.5.4.tar\libressl-2.5.4\ssl\ssl_pkt.c	305	
Warning	C4018	'<': signed/unsigned mismatch	ssl-objects	C:\Users\Dravion\Downloads\libressl-2.5.4.tar\libressl-2.5.4\ssl\ssl_pkt.c	312	
Warning	C4389	'!=': signed/unsigned mismatch	ssl-objects	C:\Users\Dravion\Downloads\libressl-2.5.4.tar\libressl-2.5.4\ssl\ssl_pkt.c	404	
Warning	C4018	'<': signed/unsigned mismatch	ssl-objects	C:\Users\Dravion\Downloads\libressl-2.5.4.tar\libressl-2.5.4\ssl\ssl_pkt.c	590	
Warning	C4146	unary minus operator applied to unsigned type, result still unsigned	ssl-objects	C:\Users\Dravion\Downloads\libressl-2.5.4.tar\libressl-2.5.4\ssl\ssl_pkt.c	708	
Warning	C4146	unary minus operator applied to unsigned type, result still unsigned	ssl-objects	C:\Users\Dravion\Downloads\libressl-2.5.4.tar\libressl-2.5.4\ssl\ssl_pkt.c	716	
Warning	C4245	'initializing': conversion from 'int' to 'const u_char', signed/unsigned mismatch	crypto-objects	C:\Users\Dravion\Downloads\libressl-2.5.4.tar\libressl-2.5.4\crypto\compat\strcasecmp.c	41	
Warning	C4702	unreachable code	openssl	c:\users\dravion\downloads\libressl-2.5.4.tar\libressl-2.5.4\apps\openssl\s_client.c	1246	
Warning	C4701	potentially uninitialized local variable 'path' used	openssl	c:\users\dravion\downloads\libressl-2.5.4.tar\libressl-2.5.4\apps\openssl\s_server.c	496	
Warning	C4703	potentially uninitialized local pointer variable 'path' used	openssl	c:\users\dravion\downloads\libressl-2.5.4.tar\libressl-2.5.4\apps\openssl\s_server.c	496	
Warning	C4701	potentially uninitialized local variable 'port' used	openssl	c:\users\dravion\downloads\libressl-2.5.4.tar\libressl-2.5.4\apps\openssl\s_server.c	497	
Warning	C4703	potentially uninitialized local pointer variable 'port' used	openssl	c:\users\dravion\downloads\libressl-2.5.4.tar\libressl-2.5.4\apps\openssl\s_server.c	497	
Warning	C4701	potentially uninitialized local variable 'host' used	openssl	c:\users\dravion\downloads\libressl-2.5.4.tar\libressl-2.5.4\apps\openssl\s_server.c	495	
Warning	C4703	potentially uninitialized local pointer variable 'host' used	openssl	c:\users\dravion\downloads\libressl-2.5.4.tar\libressl-2.5.4\apps\openssl\s_server.c	495	
Warning	C4459	declaration of 'verify_error' hides global declaration	openssl	C:\Users\Dravion\Downloads\libressl-2.5.4.tar\libressl-2.5.4\apps\openssl\s_time.c	507	
Warning	C4028	formal parameter 1 different from declaration	ssl-objects	C:\Users\Dravion\Downloads\libressl-2.5.4.tar\libressl-2.5.4\ssl\t1_lib.c	272	
Warning	C4456	declaration of 'len' hides previous local declaration	ssl-objects	C:\Users\Dravion\Downloads\libressl-2.5.4.tar\libressl-2.5.4\ssl\t1_lib.c	1784	
Warning	C4152	nonstandard extension, function/data pointer conversion in expression	crypto-objects	C:\Users\Dravion\Downloads\libressl-2.5.4.tar\libressl-2.5.4\crypto\x509\x509_vpm.c	101	
Warning	C4152	nonstandard extension, function/data pointer conversion in expression	crypto-objects	C:\Users\Dravion\Downloads\libressl-2.5.4.tar\libressl-2.5.4\crypto\x509\x509_vpm.c	102	
Warning	C4152	nonstandard extension, function/data pointer conversion in expression	crypto-objects	C:\Users\Dravion\Downloads\libressl-2.5.4.tar\libressl-2.5.4\crypto\x509\x509_vpm.c	334

**Comment by kinichiro** [comment]
I believe current code solves this issue by commit https://github.com/libressl-portable/portable/commit/94e4224f5fd17745054ee4a7e5e5b3563e144fc2 and https://github.com/libressl-portable/portable/commit/e0cffc6b4817a3325dfb4391c458d83436f96c7b .

**Comment by Dravion** [comment]
cool. I will test it ;d
