### ISSUE TITLE
tls_error() documentation in tls_read.3

### ISSUE THREAD

**Issue by github-monoculture** [libressl/portable#390]
It currently reads:
     tls_error() returns NULL if no error occurred with ctx during or since
     the last call to tls_handshake(), tls_read(), tls_write(), tls_close(),
     or tls_reset() involving ctx, or if memory allocation failed while trying
     to assemble the string describing the most recent error related to ctx.

Seems that the tls_connect*() calls should be part of that list.

**Comment by busterb** [comment]
but sure, I suppose any time the ctx has no error, tls_error should return NULL. Maybe we shouldn't try to enumerate every one of them?

**Comment by busterb** [comment]
I was just reading the source to tls_connect, and it doesn't seem call tls_error_clear at all. So, you could have an error associated with your ctx (maybe would have to do something contrived) and tls_connect, assuming it had no errors connecting, might still have the previous error set. This seems like a really weird thing to do, but I I think the docs are at least accurate.
