### ISSUE TITLE
Strange logic in crypto/compat/posix_win.c

### ISSUE THREAD

**Issue by jimpark** [libressl/portable#607]
In `posix_close()`, `posix_read()` and `posix_close()`, when the socket operation returns an error, we need to distinguish whether it was really a file operation or a true error. Why does WSANOTINITIALISED fall into calling the file function? If the fd was a socket and winsock was not initialized, that should just call wsa_errno(). I think WSAEBADF is only returned if the socket handle is bad. But if it's a file handle, it returns WSAENOTSOCK. So I think the only time we can safely call file operations is if WSAENOTSOCK is returned.

```c++
int
posix_close(int fd)
{
	if (closesocket(fd) == SOCKET_ERROR) {
		int err = WSAGetLastError();
		return err == WSAENOTSOCK ?
			close(fd) : wsa_errno(err);
	}
	return 0;
}

ssize_t
posix_read(int fd, void *buf, size_t count)
{
	ssize_t rc = recv(fd, buf, count, 0);
	if (rc == SOCKET_ERROR) {
		int err = WSAGetLastError();
		return err == WSAENOTSOCK ?
			read(fd, buf, count) : wsa_errno(err);
	}
	return rc;
}

ssize_t
posix_write(int fd, const void *buf, size_t count)
{
	ssize_t rc = send(fd, buf, count, 0);
	if (rc == SOCKET_ERROR) {
		int err = WSAGetLastError();
		return err == WSAENOTSOCK ?
			write(fd, buf, count) : wsa_errno(err);
	}
	return rc;
}
```
```

**Comment by kinichiro** [comment]
Past discussion around posix_close is here https://github.com/libressl-portable/portable/issues/266

**Comment by busterb** [comment]
See #883 this should be fixed now.
