### ISSUE TITLE
GOST R 34.12-2015 - Kuznyechik (Grasshopper) symmetric block cipher.

### ISSUE THREAD

**Issue by pedroalbanese** [libressl/portable#634]
Are there any plans to include the symmetric cipher in Libre? Would be great.

Thanks.

**Comment by joshuasing** [comment]
Hi @pedroalbanese, GOST support has been removed in LibreSSL v3.9.0, however we would be willing to reconsider if a suitable maintainer provided a modern implementation of GOST.
