### ISSUE TITLE
Merge LDAP support in s_client

### ISSUE THREAD

**Issue by Ypnose** [libressl/portable#641]
OpenSSL `1.1.1` supports `-starttls ldap` allowing us to retrieve a certificate using STARTTLS, on the standard `389` port.

OpenSSL binary from LibreSSL `LibreSSL 3.1.4` doesn't support it. It is quite convenient, especially in scripts checking certificates validity.

Here the diff from upstream :
https://github.com/openssl/openssl/commit/398b0bbdf71d852daf2e79d842cd0d307ec9f8f6

Could it possible to merge upstream change to LibreSSL ?

**Comment by busterb** [comment]
Sure, feel free to send a patch! It should go ideally to tech@openbsd.org, since this would be in the openbsd side of things.
