### ISSUE TITLE
Gost-engine issue

### ISSUE THREAD

**Issue by scaffolk** [libressl/portable#650]
As i try to sign by key generated with https://github.com/gost-engine/engine i get next issue

```
echo test | libressl dgst -streebog256 -sign openssl_gost2012_256.pem -hex
unable to load key file
140699580603208:error:0DFFF07B:asn1 encoding routines:CRYPTO_internal:header too long:asn1/asn1_lib.c:152:
140699580603208:error:0DFFF066:asn1 encoding routines:CRYPTO_internal:bad object header:asn1/tasn_dec.c:1155:
140699580603208:error:0DFFF03A:asn1 encoding routines:CRYPTO_internal:nested asn1 error:asn1/tasn_dec.c:737:
140699580603208:error:06FFF091:digital envelope routines:CRYPTO_internal:private key decode error:evp/evp_pkey.c:93:
140699580603208:error:09FFF00D:PEM routines:CRYPTO_internal:ASN1 lib:pem/pem_pkey.c:143:
```
What i do wrong? Or is it trouble of LibreSSL?

This is how i get the gost-engine key:
```
/tmp # openssl genpkey -algorithm gost2012_256 -pkeyopt paramset:A -out openssl_gost2012_256.pem
/tmp # libressl asn1parse -in openssl_gost2012_256.pem
    0:d=0  hl=2 l=  70 cons: SEQUENCE
    2:d=1  hl=2 l=   1 prim: INTEGER           :00
    5:d=1  hl=2 l=  31 cons: SEQUENCE
    7:d=2  hl=2 l=   8 prim: OBJECT            :GOST R 34.10-2012 (256 bit)
   17:d=2  hl=2 l=  19 cons: SEQUENCE
   19:d=3  hl=2 l=   7 prim: OBJECT            :id-GostR3410-2001-CryptoPro-A-ParamSet
   28:d=3  hl=2 l=   8 prim: OBJECT            :GOST R 34.11-2012 (256 bit)
   38:d=1  hl=2 l=  32 prim: OCTET STRING      [HEX DUMP]:43AFD2D473457EB1DA6C20613770B9932146B7779B325A0405977098BA9D09E1
```
There is no error if i sign it by the key from LibreSSL:
```
/tmp # libressl genpkey -algorithm gost2001 -pkeyopt dgst:streebog256 -pkeyopt paramset:A -out libressl_gost2012_256.pem
/tmp # libressl asn1parse -in libressl_gost2012_256.pem
    0:d=0  hl=2 l=  73 cons: SEQUENCE
    2:d=1  hl=2 l=   1 prim: INTEGER           :00
    5:d=1  hl=2 l=  31 cons: SEQUENCE
    7:d=2  hl=2 l=   8 prim: OBJECT            :GOST R 34.10-2012 (256 bit)
   17:d=2  hl=2 l=  19 cons: SEQUENCE
   19:d=3  hl=2 l=   7 prim: OBJECT            :id-GostR3410-2001-CryptoPro-A-ParamSet
   28:d=3  hl=2 l=   8 prim: OBJECT            :GOST R 34.11-2012 (256 bit)
   38:d=1  hl=2 l=  35 prim: OCTET STRING      [HEX DUMP]:0221009BA28B9BE631D244577A056FC7722FF8D5A87837820D0F93A45428AA4B990572
```
   
```
   echo test | libressl dgst -streebog256 -sign libressl_gost2012_256.pem -hex
(stdin)= 8f4e60010ceac873a8abcf65c7759f4e2342ec40f532eb28d3522bc061e4d84f8019b4a718eaa10ccd32501b1eb243d5be0d1023bde5c9c64105a56d5b9421f2
```

Was tried on this version https://pkgs.alpinelinux.org/package/edge/community/mips64/libressl

https://github.com/scaffolk/libregost/blob/main/pem.zip - here is PEM's

**Comment by kinichiro** [comment]
To get key you did this command,
```
/tmp # openssl genpkey -algorithm gost2012_256 -pkeyopt paramset:A -out openssl_gost2012_256.pem
```
But I got this error below both with LibreSSL 3.3.1 and OpenSSL 1.1.1i.
```
Algorithm gost2012_256 not found
```
Is your above command line option right ?

**Comment by scaffolk** [comment]
OpenSSL doesn't have realization of GOST 34.11-2012
Algorithms of GOST are parts of GOST-engine.
https://github.com/gost-engine/engine 
which also available in ubuntu/debian 
https://packages.debian.org/sid/libengine-gost-openssl1.1 и fedora
https://koji.fedoraproject.org/koji/packageinfo?packageID=27720

For enabling GOST-engine in ubuntu:

apt install openssl libengine-gost-openssl1.1
sed -i '20i openssl_conf=openssl_init' /etc/ssl/openssl.cnf

echo '\n\
[openssl_init]\n\
engines = engine_section\n\
\n\
[engine_section]\n\
gost = gost_section\n\
\n\
[gost_section]\n\
engine_id = gost\n\
default_algorithms = ALL\n\
CRYPT_PARAMS = id-Gost28147-89-CryptoPro-A-ParamSet\n'\
>> /etc/ssl/openssl.cnf

Checking gost-engine:
openssl ciphers|tr ':' '\n'|grep GOST

Also you can use the readme
https://github.com/gost-engine/engine/blob/master/README.gost

**Comment by joshuasing** [comment]
GOST is no longer supported as of LibreSSL v3.9.0.
