### ISSUE TITLE
Need help. Can't enable gost algorithms when using LibreSSL with cURL

### ISSUE THREAD

**Issue by kartaris** [libressl/portable#679]
I have built LibreSSL statically to be able to include it into an iOS application.
And now I have a problem. When I try to connect to "https://gost.cryptopro.ru" using curl, non-gost ciphering selected. 
Think I'm doing something wrong.
Here is my code sample
```
...
    OpenSSL_add_all_ciphers();
    OpenSSL_add_all_algorithms();

    CURLcode res;
    std::string readBuffer;

    CURL *curl = curl_easy_init();
    if(!curl)
        return 1;

    curl_easy_setopt(curl, CURLOPT_URL,  "https://gost.cryptopro.ru");
    curl_easy_setopt(curl, CURLOPT_WRITEFUNCTION, WriteCallback);
    curl_easy_setopt(curl, CURLOPT_WRITEDATA, &readBuffer);
    curl_easy_setopt(curl, CURLOPT_VERBOSE, true);
    curl_easy_setopt(curl, CURLOPT_SSL_VERIFYPEER, false);
    curl_easy_setopt(curl, CURLOPT_SSL_VERIFYHOST, false);

    res = curl_easy_perform(curl);
    if(res != CURLE_OK)
    {
        std::cout << res;
        return 1;
    }
    curl_easy_cleanup(curl);

    std::cout << readBuffer << std::endl;
...
```

PS: Also I've found that application binary in apps/openssl connects to the server and correct ciphering used, that's why I think I need to do something else.

**Comment by kartaris** [comment]
I tired rebuilding cUrl with some flags for ssl and cUrl fails with the next problem:
`* error:1401E41A:SSL routines:CONNECT_CR_FINISHED:tlsv1 alert decode error`

**Comment by kartaris** [comment]
> I tired rebuilding cUrl with some flags for ssl and cUrl fails with the next problem:
> `* error:1401E41A:SSL routines:CONNECT_CR_FINISHED:tlsv1 alert decode error`

I'm getting the same error when using cURL's binary.

cURL version: 7.78.0(built as static library)
LibreSSL version:  3.3.2(built as static library)
OS: Tried on Ubuntu 18.04(trying to get working solution on Linux before porting to iOS)

**Comment by kartaris** [comment]
> > I tired rebuilding cUrl with some flags for ssl and cUrl fails with the next problem:
> > `* error:1401E41A:SSL routines:CONNECT_CR_FINISHED:tlsv1 alert decode error`
> 
> I'm getting the same error when using cURL's binary.
> 
> When I call `./apps/openssl/openssl s_client -connect gost.cryptopro.ru:443` it connects to server, dumps certificate and returns certificate verification error(but it's OK, cause I haven't installed some):
> 
> ```
> SSL handshake has read 2333 bytes and written 213 bytes
> ---
> New, TLSv1/SSLv3, Cipher is GOST2012256-GOST89-GOST89
> Server public key is 256 bit
> Secure Renegotiation IS supported
> Compression: NONE
> Expansion: NONE
> No ALPN negotiated
> SSL-Session:
>     Protocol  : TLSv1.2
>     Cipher    : GOST2012256-GOST89-GOST89
>     Session-ID: 
>     Session-ID-ctx: 
>     Master-Key: 9FA4A79F9129A919B3676D0C95DE769C39155379A439246BF774B6ED988C729D7D9A3B869B5EC096483FCE927CD7E272
>     Start Time: 1628517907
>     Timeout   : 7200 (sec)
>     Verify return code: 21 (unable to verify the first certificate)
> ---
> ```
> 
> cURL version: 7.78.0(built as static library)
> LibreSSL version: 3.3.3(built as static library)
> OS: Tried on Ubuntu 18.04(trying to get working solution on Linux before porting to iOS)

Here is the packets captured by wireshark: [gost.cryptopro.ru_curl-libressl.zip](https://github.com/libressl-portable/portable/files/6959653/gost.cryptopro.ru_curl-libressl.zip)
As I can see, server can't decode the message sent by client.

And here is the correct server-client communication example(chromium-gost browser):
[gost.cryptopro.ru_chromium-gost.zip](https://github.com/libressl-portable/portable/files/6959676/gost.cryptopro.ru_chromium-gost.zip)

**Comment by kartaris** [comment]
https://github.com/gost-engine/engine/issues/340#issuecomment-895943881

Current LibreSSL version doesn't support recent standarts, that's why it fails.

**Comment by joshuasing** [comment]
Hi @kartaris, GOST support has been removed in LibreSSL v3.9.0, however we would be willing to reconsider if a suitable maintainer provided a modern implementation of GOST.
