### ISSUE TITLE
Library not found on Windows due to version postfix

### ISSUE THREAD

**Issue by ccvca** [libressl/portable#681]
In #219 a version-postfix was introduced to the library on windows.

https://github.com/libressl-portable/portable/blob/7072a55b80256357b0f0da1ce55e2de6de517ae7/ssl/CMakeLists.txt#L74-L76
https://github.com/libressl-portable/portable/blob/7072a55b80256357b0f0da1ce55e2de6de517ae7/crypto/CMakeLists.txt#L1007-L1009
https://github.com/libressl-portable/portable/blob/7072a55b80256357b0f0da1ce55e2de6de517ae7/tls/CMakeLists.txt#L60-L62

But this causses problems in the find-Script, as only the "clean" version is searched.

https://github.com/libressl-portable/portable/blob/7072a55b80256357b0f0da1ce55e2de6de517ae7/FindLibreSSL.cmake#L105-L114

I had success by manually renaming the installed libraries, but this is quite hard in a CI context.

Why is this postfix applied on windows?

**Comment by Borwe** [comment]
Just arrived at same problem. It becomes a problem in CI true.

**Comment by zzzjim** [comment]
Changing them to:

set(SSL_POSTFIX -${SSL_MAJOR_VERSION} PARENT_SCOPE)
set(CRYPTO_POSTFIX -${CRYPTO_MAJOR_VERSION} PARENT_SCOPE)
set(TLS_POSTFIX -${TLS_MAJOR_VERSION} PARENT_SCOPE)

Along with
cmake -DSSL_POSTFIX:String= -DTLS_POSTFIX:String= -DCRYPTO_POSTFIX:String= .

Makes it go away.
