### ISSUE TITLE
Incorrect compiler flags set in debug builds for MSVC and CMake

### ISSUE THREAD

**Issue by mharmer** [libressl/portable#683]
The following warning was observed when attempting to build a debug build with CMake/Ninja/MSVC:
```
cl : Command line warning D9025 : overriding '/O2' with '/Od'
```

I believe this line in CMakeLists.txt is causing this:
```
set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -O2 -Wall")
```
It appears this was originally added with e7d11ba. These compiler flags seem to be gcc/clang specific, however the "-O2" is interpreted by MSVC as "/O2", which gets overridden by the specified "/Od" flag when configuring CMake as a debug build via:
```
cmake ..\libressl-3.3.4 -DCMAKE_BUILD_TYPE=Debug -G Ninja
```

One approach to solving this is changing the CMakeLists.txt line to:
```
if(NOT MSVC)
	set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -O2 -Wall")
endif()
```

Additionally, I'm not sure the optimization flag should be changed like this, I think generally they should rely on the CMake system to set them. Generally, I believe CMake will set the appropriate optimization level provided the `CMAKE_BUILD_TYPE`.

**Comment by busterb** [comment]
Nice find, I think we should remove them and let CMake / the user set the optimization level.
