### ISSUE TITLE
what are the stack requirements for LibreSSL?

### ISSUE THREAD

**Issue by markjolesen** [libressl/portable#691]
I maintain a DOS port. It is blowing up with not enough stack space. The previous version did not do this. I can not trace because WATTCP injects it's own stack tracing, which turns out to not give out information..

**Comment by busterb** [comment]
The smallest stack size on OpenBSD is 4M. LibreSSL has to fit in here + whatever code you might be calling it with.
You might, and probably, can get by with less, but I don't think we be able to guarantee it.

You might just have to bisect on your end if you need to fit it into a particular constraint.
