### ISSUE TITLE
Proper use of EVP_add_digest()

### ISSUE THREAD

**Issue by ronaaron** [libressl/portable#756]
I was hoping to be able to add BLAKE2s as an additional digest option, and it seemed that EVP_add_digest() would be just the thing.

But it's not, because there's no 'name' so it crashes inside EVP_add_digest().

Is there a way for an application to add a cipher or digest without recompiling the entire library?

**Comment by ronaaron** [comment]
So what _does_ work is simply creating the EVP_MD structure as appropriate, and returning it to be used.

For name lookup it doesn't work, so I have some additional lookup code if EVP_get_digestbyname() returns NULL.

**Comment by botovq** [comment]
I think the answer here is in order to make EVP_get_digestbyname() work, you need to call OBJ_create() with the proper OID, short and long name from RFC 7693, use the returned nid to create  the EVP_MD with EVP_MD_method_new() and then EVP_add_digest().
