### ISSUE TITLE
suspected memory leak on LibreSSL-3.5.2

### ISSUE THREAD

**Issue by chipitsine** [libressl/portable#758]
I'm playing with valgrind checks on certain execution path for haproxy

https://github.com/chipitsine/haproxy/runs/6352202532?check_suite_focus=true#step:15:8485

valgrind findings for LibreSSL differ a bit from other SSL libs.
can someone skilled in LibreSSL have a look ?

**Comment by botovq** [comment]
LibreSSL installs no atexit handler. You need to call OPENSSL_cleanup() manually. Could you try that?

**Comment by chipitsine** [comment]
I do not encounter that on current master
