### ISSUE TITLE
Current Windows build

### ISSUE THREAD

**Issue by OCram85** [libressl/portable#772]
Hey folks,
just wanted to update the embedded libressl-portable binary in my project [PSCredentialStore](https://gitea.ocram85.com/OCram85/PSCredentialStore).
Is there any way to download the latest release as a windows binary?

**Comment by Kreijstal** [comment]
try building it on mingw

**Comment by OCram85** [comment]
I tried to build it locally but couldn't get it running. I'm completely unfamiliar with the tools needed therefore (mingw, vscode based builds).
Maybe it's worth trying to set up a AppVeyor based pipeline for the windows builds?

**Comment by chipitsine** [comment]
there's AppVeyor: https://ci.appveyor.com/project/busterb/portable/builds/44612706
definition: https://github.com/libressl-portable/portable/blob/master/appveyor.yml

**Comment by OCram85** [comment]
@chipitsine: I've looked into the build artifacts from recent builds. The `Testing.zip` just contains some logs. Shouldn't it also contain the binaries?

**Comment by chipitsine** [comment]
I bet the idea was to provide binaries on successful build and logs for failed build.

I'll have a look

**Comment by chipitsine** [comment]
@OCram85 , I've [changed](https://github.com/chipitsine/portable/commit/2e9adeeeaec26ff0d6588d2831171676b0c9da69) artifacts settings in my fork, please [check](https://ci.appveyor.com/project/chipitsine/portable-ri28j/builds/44736112) whether it is good for you

if ok, I'll make a PR

**Comment by OCram85** [comment]
@chipitsine: Awesome! Is it possible to attach a script which greps the libs /  binaries _(libcryptro*,libssl*, libtls*, openssl.exe)_ to get the portable win version?

**Comment by chipitsine** [comment]
as for portable windows version I guess it worth separate task.
currently artifacts are not very comfortable for using and pipeline runs on evry pull request/push.

probably, windows portable should be packaged on git tags (??), also, some versioninng should happen. and final destination should be chocolatey instead of artifacts.


I'll have a look whether appveyor allows to specify file extension filters

**Comment by chipitsine** [comment]
PR created: https://github.com/libressl-portable/portable/pull/789

**Comment by OCram85** [comment]
btw... what files do I need from the artifacts folder to get a usable `openssl.exe` / libressl ?
The last windows portable build I found was v2.5.5:

![image](https://user-images.githubusercontent.com/13993700/190592016-ea491f64-ecdf-4b83-b58b-e0ba4f2b92b4.png)

**Comment by chipitsine** [comment]
I suggest to put `libressl.exe` to empty folder and run it.

alternatively, [dependency walker ](https://stackoverflow.com/questions/1993673/what-is-the-equivalent-of-linuxs-ldd-on-windows) can help

**Comment by chipitsine** [comment]
"pdb" files are required for debugging purpose.

**Comment by OCram85** [comment]
Thank you for all the help.
I guess it works now for me [OCram85/libressl-portable](https://github.com/OCram85/libressl-portable/blob/master/appveyor.yml). _(`x64 build` + `SHARED_LIBS=OFF`)_

**Comment by chipitsine** [comment]
I played with app veyor on releases. `secure: PD+DR9Pb8syGAOUjJ6Y5d07AXR6btDzWreuPKcAOwxgANFcIrhcaABSHvsju+nrI` is repo specific.

no easy way to make it friendly for forks and pull requests.

but it is good you made portable )) what I think, maybe switch to github actions (it is more friendly with secrets)... and push portable to chocolatey

**Comment by busterb** [comment]
I merged the change to retain build artifacts from appveyor, though more for the potential to make debugging build failures there easier. That's an interesting change @OCram85. I haven't played with github actions for Windows builds, I wonder if they would be better for archiving release artifacts.

**Comment by busterb** [comment]
as of #878 we now have a Windows builder github action. Is there a better way to archive tagged release builds with this mechanism? Can we stop building on Appveyor? I think the answer is yes for both, but wanted to check with you all.

**Comment by OCram85** [comment]
> as of #878 we now have a Windows builder github action. Is there a better way to archive tagged release builds with this mechanism? Can we stop building on Appveyor? I think the answer is yes for both, but wanted to check with you all.

Awesome, I also prefer using github actions. Do you plan to upload the windows build artifacts in the tag based github release page?

**Comment by busterb** [comment]
sure @chipitsine that would be fine if you want to send a PR. I'm honestly just fumbling about with GHA, so if you already know how to do it, that helps!

**Comment by OCram85** [comment]
@sergeevabc: Did it work for you?

**Comment by sergeevabc** [comment]
@OCram85, yes! It was no coincidence that I marked your previous message with a hooray icon. Just in case, I’ll attach [libressl_v382_binary.zip](https://github.com/libressl/portable/files/13614314/libressl_v382_binary.zip) here to make things easier for those who are desperately looking for one.

``` console
$ openssl.exe version
LibreSSL 3.8.2
```

**Comment by chipitsine** [comment]
I planned to make GHA release, but didn't have time yet.
let me try next weekend

**Comment by chipitsine** [comment]
here we go
https://github.com/libressl/portable/pull/965

**Comment by sergeevabc** [comment]
> here we go #965

It works as expected, thank you. Just LibreSSL from 3.8.2 to 3.9.2.
