### ISSUE TITLE
EVP_CIPHER Opacity

### ISSUE THREAD

**Issue by rapier1** [libressl/portable#790]
Hey there, 

In some of my code I was, up until version 3.5, able to modify the functions of the EVP_CIPHER by modifying the function pointers in the struct. E.g,
```
static EVP_CIPHER aes;
aes.init = my_aes_init;
aes.do_cipher = my_aes_do;
```
This now fails. I'm assuming that's because struct has been made opaque. When OpenSSL did the same thing they still allowed the struct's functions pointers to be modified by using EVP_CIPHER_meth_new() and, for example, EVP_CIPHER_meth_set_init(); I've not yet been able to find equivalent functionality in the LibreSSL 3.5 code base as of yet. I see you have _meth_new for EVP_MD, BIO, etc but not EVP_CIPHER. Am I missing something, is this something that is in development, on your radar, or won't be implemented?

**Comment by botovq** [comment]
Could you elaborate on your use case for this?

We generally add pieces of the OpenSSL 1.1 API if we run into software
using them. According to debian codesearch, there are very few things
that make use of the EVP_CIPHER_meth_* setters and getters and even
fewer that have use cases that we want to support. None of the code
paths reached by the OpenBSD ports tree use them. Therefore we haven't
seen a need to add them.

While adding them would be easy enough, it is too late for the 3.6
release.

**Comment by rapier1** [comment]
Sure thing. I am the lead developer of HPN-SSH (https://github.com/rapier1/openssh-portable). This a fork of OpenSSH specifically designed for high performance networks and computation. It's in pretty wide distribution in the HPC community as it as been rolled into gsissh, which is included in the default EPEL and Fedora package list. 

Anyway, one of the ways we've accelerated performed was to parallelize the AES-CTR cipher. Essentially, we precompute the key stream and store the results in a series of queues that we rotate through as we get data to en|decipher. At that point all we need to do is pull the corresponding block off of the queue and xor it. This necessarily means that we had to develop our own set_init, cleanup, and do-cipher functions to support this. See https://github.com/rapier1/openssh-portable/blob/master/cipher-ctr-mt.c if you want the details. 

I'd very much like to continue supporting LibreSSL but I understand if this use case is too narrow for you to address.

**Comment by botovq** [comment]
Thanks for the explanation. It is a bit of a fringe use case, but on the
other hand, a handful of setters more won't make libcrypto fatter than
it already is...

The timing is unfortuante in that we have just entered ABI lock a few
days ago and will release LibreSSL 3.6 soon, so it will definitely be
impossible for you to support LibreSSL 3.5 and 3.6.

If you would be willing to continue supporting LibreSSL <= 3.4 or at
least add back support for LibreSSL 3.7 once it is out (April or May
next year), I will in turn revisit this in the next release cycle. I
will need to discuss with the other developers if we can to add some of
the EVP_CIPHER_meth_set_* functions for 3.7 - I can't take this decision
on my own.

**Comment by rapier1** [comment]
I would be more than happy to put in carve outs for 3.5 and 3.6. Not bringing this up earlier is just bad timing on my part. I appreciate you taking the time to bring this up with the other developers. 

One more question, and you can pass on this if you like; I'm not as familiar with how LibreSSL reports the version number. In the configure.ac used (inherited from OpenSSH) LibreSSL seems to just report that back as 0x20000000 for any version. Is there a decent programatic way to get the full version number from Libre?

**Comment by botovq** [comment]
Great, thanks!

OPENSSL_VERSION_NUMBER should never change in LibreSSL. The idea was to encourage feature checks via autoconf or similar, but that didn't work out so well...

The ordinary way to check for a LibreSSL version via the preprocessor would be to use some variant of

```
#if (defined(LIBRESSL_VERSION_NUMBER) && LIBRESSL_VERSION_NUMBER < 0x3050000fL)
```

see [the manual](https://man.openbsd.org/OPENSSL_VERSION_NUMBER) or [the `opensslv.h` header](https://github.com/libressl-portable/openbsd/blob/fbf5e3067f7966178941fb933f17dbc145135d50/src/lib/libcrypto/opensslv.h) for more details.

**Comment by rapier1** [comment]
Sweet. I'll try getting those incorporated today.

**Comment by rapier1** [comment]
Thanks again for the help. HPN-SSH now specifically checks for the LibreSSL version number and if it's 3.5 or 3.6 it will fall back to the serial implementation of AES CTR. Please let me know if the EVP_CIPHER_meth_new/set functions will end up in 3.7 when you know. 

Chris

**Comment by botovq** [comment]
Yes, OPENSSL_VERSION_NUMBER should never change in LibreSSL. The idea
was to encourage feature checks via autoconf or similar, but that didn't
work out so well.

The ordinary way to check for a LibreSSL version via the preprocessor
would be to use some variant of

#if (defined(LIBRESSL_VERSION_NUMBER) && LIBRESSL_VERSION_NUMBER < 0x3050000fL)

see https://man.openbsd.org/OPENSSL_VERSION_NUMBER for more details.

**Comment by nmaya** [comment]
Hi,

Our project (Tera Term/TTSSH) uses LibreSSL to SSH ciphers too.
It supports CTR ciphers, and be affected by opaque.
I hope LibreSSL support EVP_CIPHER_meth_* functions.

Thanks,

**Comment by botovq** [comment]
As promised, I have [landed][1] the `EVP_CIPHER_meth_set_*` parts of the API since that's what your projects appear to use. They will be exposed with the next library bump and should be available at the latest with the -stable release of the 3.7 branch. I do not know if it will make 3.7.1.

[1]: https://github.com/openbsd/src/blob/9fb10e5c48f6d6738f5df147b8e526c7ef4440ac/lib/libcrypto/evp/cipher_method_lib.c

**Comment by rapier1** [comment]
Sweet! Thank you! I'll keep an eye out for it.

**Comment by rapier1** [comment]
Just wanted to let you know that I found it in the 3.7.1 release and have incorporated it back into hpnssh. That version (17v12) should be released tomorrow. I'm also going to backport it into the current version (17v11) as it's just a configure.ac change. Thanks again for all of the work.

**Comment by 4a6f656c** [comment]
@rapier1 - thanks for letting us know.
