### ISSUE TITLE
Compiling with tag v3.6.2: Reversed (or previously applied) patch detected!  Assume -R? [n]

### ISSUE THREAD

**Issue by skygunner** [libressl/portable#823]
`Hunk #1 succeeded at 667 (offset 1 line).
Hunk #2 succeeded at 697 (offset 1 line).
patching file crypto/bn/bn_div.c
patching file tests/bn_isqrt.c
patching file ./crypto/bn/bn_lcl.h
patching file tests/handshake_table.c
patching file crypto/modes/modes_lcl.h
patching file apps/nc/netcat.c
patching file tests/ocsp_test.c
patching file apps/openssl/openssl.c
patching file tests/rfc5280time.c
patching file apps/openssl/speed.c
patching file ssl/ssl_txt.c
patching file include/tls.h
patching file tests/tlsexttest.c
patching file include/openssl/dtls1.h
patching file include/openssl/opensslconf.h
patching file include/openssl/ossl_typ.h
patching file include/openssl/pkcs7.h
patching file include/openssl/x509.h
patching file x509/x509_genn.c
Reversed (or previously applied) patch detected!  Assume -R? [n]
`

**Comment by busterb** [comment]
Duplicate issue as #814
