### ISSUE TITLE
Arch specific opensslconf.h is problematic on Gentoo multilib

### ISSUE THREAD

**Issue by orbea** [libressl/portable#828]
This issue has been reported for libressl-3.7.1 on Gentoo multilib systems.

https://github.com/gentoo/libressl/issues/506

Which appears to be related to making `opensslconf.h` arch specific which results in the file being different on different architectures triggering an error in the gentoo multlib eclass.

https://github.com/libressl/portable/commit/3c7747fd8bcaaf2eb2f901c34d573bae52fea0c5

Is this required to be done this way? Can't the arch specific changes just be handled via preprocessor?

**Comment by 4a6f656c** [comment]
LibreSSL has always had per architecture `opensslconf.h` files, however until recently portable seems to have incorrectly used the amd64 version for all versions. We're unlikely to use preprocessor directives here, as that makes management and changes far more complex (particularly with respect to testing across architectures).

I'm not sure that I understand the exact use case, however if you're installing multiple versions of the same library, can you not handle multiple/differing headers as part of that process? Alternatively, the opensslconf.h headers could presumably be concatenated together with processor directives, if you really wanted to do that locally.

**Comment by orbea** [comment]
> however until recently portable seems to have incorrectly used the amd64 version for all versions.

Thanks for explaining, I didn't realize this was a problem, but I am still wondering if there is perhaps a cleaner way of handling this?

> I'm not sure that I understand the exact use case, however if you're installing multiple versions of the same library, can you not handle multiple/differing headers as part of that process?

On linux multilib systems there be libraries that are builti for more than one architecture on a single system, i686 and amd64 for instance is commonly used for wine. Reading documentation for Gentoo it seems possible to workaround this, but I am not yet sure how....

https://wiki.gentoo.org/wiki/Multilib/Concepts#Header_files

> Alternatively, the opensslconf.h headers could presumably be concatenated together with processor directives, if you really wanted to do that locally.

While that does sound possible, it certainly sounds like one of the least ideal solutions.

**Comment by orbea** [comment]
It seems Gentoo might have a solution for this with their `MULTILIB_WRAPPED_HEADERS` eclass variable, but its documentation suggests this is discouraged. I am unsure if this may have side effects for Gentoo or if its a real problem for libressl or not?
 > A list of headers to wrap for multilib support. The listed headers will be moved to a non-standard location and replaced with a file including them conditionally to current ABI.
>
> This variable has to be a bash array. Paths shall be relative to installation root (${ED}), and name regular files. Recursive wrapping is not supported.
>
> Please note that header wrapping is *discouraged*. It is preferred to install all headers in a subdirectory of libdir and use pkg-config to locate the headers. Some C preprocessors will not work with wrapped headers. 

https://devmanual.gentoo.org/eclass-reference/multilib-build.eclass/index.html

**Comment by orbea** [comment]
Are there any further comments on this? Would Gentoo's suggestion of `"It is preferred to install all headers in a subdirectory of libdir and use pkg-config to locate the headers."` be a plausible improvement or is this acceptable as is where the issue should be closed?

**Comment by busterb** [comment]
I think your approach of having a wrapper is fine if you want to do it that way. 

Note, multilib on Debian just installs each in a subdirectory in the include dir and the compiler puts the right one in the search path instead:

```
$ dpkg -S opensslconf.h|grep libssl
libssl-dev:amd64: /usr/include/x86_64-linux-gnu/openssl/opensslconf.h
libssl-dev:i386: /usr/include/i386-linux-gnu/openssl/opensslconf.h
```

**Comment by busterb** [comment]
I'm not sure what Kibana is doing, but I hope it's OK!

```
kibana: /usr/share/kibana/node/include/node/openssl/archs/aix64-gcc/asm/include/openssl/opensslconf.h
kibana: /usr/share/kibana/node/include/node/openssl/archs/linux-aarch64/asm_avx2/include/openssl/opensslconf.h
kibana: /usr/share/kibana/node/include/node/openssl/archs/darwin64-x86_64-cc/asm_avx2/include/openssl/opensslconf.h
kibana: /usr/share/kibana/node/include/node/openssl/archs/linux64-s390x/asm/include/openssl/opensslconf.h
kibana: /usr/share/kibana/node/include/node/openssl/archs/VC-WIN64A/asm_avx2/include/openssl/opensslconf.h
kibana: /usr/share/kibana/node/include/node/openssl/archs/linux64-riscv64/no-asm/include/openssl/opensslconf.h
kibana: /usr/share/kibana/node/include/node/openssl/archs/linux64-mips64/no-asm/include/openssl/opensslconf.h
kibana: /usr/share/kibana/node/include/node/openssl/archs/linux-ppc64/asm_avx2/include/openssl/opensslconf.h
kibana: /usr/share/kibana/node/include/node/openssl/archs/linux-x86_64/no-asm/include/openssl/opensslconf.h
kibana: /usr/share/kibana/node/include/node/openssl/archs/linux-armv4/asm/include/openssl/opensslconf.h
kibana: /usr/share/kibana/node/include/node/openssl/archs/darwin-i386-cc/asm/include/openssl/opensslconf.h
kibana: /usr/share/kibana/node/include/node/openssl/archs/linux-x86_64/asm_avx2/include/openssl/opensslconf.h
kibana: /usr/share/kibana/node/include/node/openssl/archs/linux64-mips64/asm_avx2/include/openssl/opensslconf.h
kibana: /usr/share/kibana/node/include/node/openssl/archs/linux64-mips64/asm/include/openssl/opensslconf.h
kibana: /usr/share/kibana/node/include/node/openssl/archs/solaris-x86-gcc/asm/include/openssl/opensslconf.h
kibana: /usr/share/kibana/node/include/node/openssl/archs/BSD-x86_64/asm/include/openssl/opensslconf.h
kibana: /usr/share/kibana/node/include/node/openssl/archs/darwin-i386-cc/asm_avx2/include/openssl/opensslconf.h
kibana: /usr/share/kibana/node/include/node/openssl/archs/linux-ppc64le/asm_avx2/include/openssl/opensslconf.h
```

**Comment by busterb** [comment]
Either way, I don't think there's much to do on the LibreSSL end other than note that you'll want to somehow make sure the right version is available to the correct architecture. Will close this for now.
