### ISSUE TITLE
libressl 3.7.x doesn't provide EVP_sha512_256()

### ISSUE THREAD

**Issue by orbea** [libressl/portable#832]
When building neon `0.32.4` it fails because libressl doesn't provide `EVP_sha512_256()`. Is there a reason libressl does not have this function? Or is it just that it has not been done yet?

I made a PR for neon to workaround the issue for now. https://github.com/notroj/neon/pull/113

**Comment by botovq** [comment]
On Sat, Apr 01, 2023 at 12:46:42PM -0700, orbea wrote:
> When building neon `0.32.4` it fails because libressl doesn't provide `EVP_sha512_256()`. Is there a reason libressl does not have this function? Or is it just that it has not been done yet?

No reason, except no-one has done the work - it wasn't all that widely
used and there is no protocol that strictly requires it that wouldn't
also work wish hases we also offer.

There are concrete plans to add it soon.

For the time being neon will need to be patched. The OpenBSD ports tree
took a more brutal and not upstreamable approach...

https://github.com/openbsd/ports/blob/91f0187c892a503438b85e2d580b8a969fd308ac/net/neon/patches/patch-src_ne_openssl_c

> I made a PR for neon to workaround the issue for now. https://github.com/notroj/neon/pull/113

Thank you. Your help with keeping upstreams working with LibreSSL is
quite visible and much appreciated.

**Comment by orbea** [comment]
> There are concrete plans to add it soon.

Thanks for the info and glad to hear this!

> Thank you. Your help with keeping upstreams working with LibreSSL is
quite visible and much appreciated.

I have only done what little I can to keep my systems running, but I'm glad its appreciated. Unfortunately I don't have the hardware to run a Gentoo tinderbox to find more issues.

**Comment by job** [comment]
Should be available in the next release https://github.com/libressl/openbsd/commit/8dff3535f4db62f83e7a2781d82f87c7526cc16c

**Comment by 4a6f656c** [comment]
This is available in LibreSSL 3.8.0.

**Comment by orbea** [comment]
Indeed, I can confirm the neon build succeeds with LibreSSL 3.8.0 and made a followup PR for upstream.

https://github.com/notroj/neon/pull/118
