### ISSUE TITLE
libressl 3.7.x doesn't support SSL_export_keying_material_early()

### ISSUE THREAD

**Issue by orbea** [libressl/portable#836]
OpenLDAP depends on `SSL_export_keying_material_early` during the configure check (Even though they don't even use it).

I tried to fix this upstream, but apparently this is intentional to prevent the use of older OpenSSL APIs. Are there any plans to support this in LibreSSL?

https://git.openldap.org/openldap/openldap/-/merge_requests/612
https://bugs.openldap.org/show_bug.cgi?id=10039

**Comment by botovq** [comment]
No, there are no plans to add this. SSL_CTX_set_ciphersuites() would
have worked just as well for the stated purpose.

**Comment by orbea** [comment]
OpenLDAP merged the compromise so I will close this issue at least until a less trivial of this function is found.

https://git.openldap.org/openldap/openldap/-/commit/cb73e60a49f85bf5207b2fd0f557013be29ac072
