### ISSUE TITLE
incompatibility with openssl 3.0 version

### ISSUE THREAD

**Issue by jogme** [libressl/portable#846]
Is there a possibility to add support for OSSL_* API specifically OSSL_PARAM and OSSL_PARAM_BLD introduced in openssl 3.0 version?

Currently OpenSSH blocked some useful changes because of the incompatibility of the changes with LibreSSL.

**Comment by 4a6f656c** [comment]
LibreSSL is incompatible with OpenSSL 3.0, in the same way that OpenSSL 1.1 is incompatible with OpenSSL 3.0. Saying that it is incompatible is not really a useful assertion on its own. In general, LibreSSL does not add new API (especially poorly designed ones) without a very good reason to do so. Simply saying that "OpenSSH blocked some useful changes" does not provide any relevant details, let alone a justification.

**Comment by orbea** [comment]
> Currently OpenSSH blocked some useful changes because of the incompatibility of the changes with LibreSSL.

What useful changes? Can you please explain further?

**Comment by jogme** [comment]
Thank you for your comments. 

For OpenSSH - as it is among the base packages of a linux system - it is useful to provide FIPS compliance satisfying governmental and other high expectation customers (banks, healthcare etc.). LibreSSL implements EVP API which in extension of some additional API could be well aligned to easily provide FIPS compliance with OpenSSL to OpenSSH. The support of the mentioned API would reduce the cost of OpenSSH maintenance for this FIPS change as well as for the fact that the low level OpenSSL API is deprecated and will be eliminated in the future. This raises a question of how to keep compatibility without much issue and changing to EVP API would be a good solution.

Fedora already implements these changes in OpenSSH via a downstream patch, but switching upstream to EVP API would have much more benefits. We in Fedora are ready to implement it, but it needs to align with the needs of OpenSSH upstream which is at the moment not met.

**Comment by bob-beck** [comment]
So realistically what you are asking is to convert OpenSSH to the EVP api..   It is not necessary for LibreSSL to make changes to support that happening, as LibreSSL includes support for EVP.  It is merely necessary for OpenSSH to convert to using the EVP api from the raw api's currently in use..  

There is no need to add OpenSSL 3.0 support for that to happen.. EVP exists in the 1.1.1 API and is supported by LibreSSL and OpenSSL 3.X
