### ISSUE TITLE
Libressl accepts digital certificate with version 1

### ISSUE THREAD

**Issue by llmlla** [libressl/portable#853]
When I used LibreSSL for certificate validation I found that LibreSSL accepted a digital certificate with version 1. RFC 5280 mentions that the version must be 3. 
The version of LibreSSL I have used is 3.4.1. Here is commond i used:
`openssl verify -CAfile root.pem leaf.pem`
Here are certificates file i used.
[leaf.txt](https://github.com/libressl/portable/files/11403088/leaf.txt)
[root.txt](https://github.com/libressl/portable/files/11403090/root.txt)

**Comment by botovq** [comment]
RFC 5280 does not mention that the version must be 3. It must be 3 if extensions are present. It is questionable how much benefit a check for this brings, but we added one recently: https://github.com/libressl/openbsd/commit/47b20828782a0ab461ce852a03b3e7bd75e44fe2
