### ISSUE TITLE
Undefined symbols for architecture x86_64:   "_be64toh", referenced from: _sha512_block_data_order in libcrypto_la-sha512.o ld: symbol(s) not found for architecture x86_64

### ISSUE THREAD

**Issue by vollkommenheit** [libressl/portable#858]
On macOS Intel, my last successful compile was on 5/13. Today, I'm getting the following errors, which seem to be resulting from https://github.com/libressl/portable/commit/765a8fac94fece34cead0bd03f89bdb1b8c43da6

>   CCLD     libcrypto.la
Undefined symbols for architecture x86_64:
  "_be64toh", referenced from:
      _sha512_block_data_order in libcrypto_la-sha512.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [libcrypto.la] Error 1
make[1]: *** [check] Error 2
make: *** [check-recursive] Error 1
start make...
Making all in include
Making all in openssl
/Applications/Xcode.app/Contents/Developer/usr/bin/make  all-am
make[3]: Nothing to be done for `all-am'.
make[2]: Nothing to be done for `all-am'.
Making all in crypto
/Applications/Xcode.app/Contents/Developer/usr/bin/make  all-am
  CCLD     libcrypto.la
Undefined symbols for architecture x86_64:
  "_be64toh", referenced from:
      _sha512_block_data_order in libcrypto_la-sha512.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [libcrypto.la] Error 1
make[1]: *** [all] Error 2
make: *** [all-recursive] Error 1

Not sure if the warnings below were present before today, but earlier during the 'make':
>   CC       libcrypto_la-crypto_lock.lo
In file included from crypto_lock.c:22:
./crypto_internal.h:41:9: warning: implicit declaration of function 'be32toh' is invalid in C99 [-Wimplicit-function-declaration]
        return be32toh(v);
               ^
./crypto_internal.h:72:9: warning: implicit declaration of function 'be64toh' is invalid in C99 [-Wimplicit-function-declaration]
        return be64toh(v);
               ^
2 warnings generated.
  CC       libcrypto_la-cversion.lo

>   CC       bn/libcrypto_la-bn_isqrt.lo
In file included from bn/bn_isqrt.c:25:
./crypto_internal.h:41:9: warning: implicit declaration of function 'be32toh' is invalid in C99 [-Wimplicit-function-declaration]
        return be32toh(v);
               ^
./crypto_internal.h:72:9: warning: implicit declaration of function 'be64toh' is invalid in C99 [-Wimplicit-function-declaration]
        return be64toh(v);
               ^
2 warnings generated.
  CC       bn/libcrypto_la-bn_kron.lo

Possible fix:
If I replace all the `#defines` in the `#if defined(__APPLE__) && !defined(HAVE_ENDIAN_H)` section of `include/compat/endian.h` with those from the `#ifdef __APPLE__` section of `src/endian_compat.h` at https://github.com/DNS-OARC/dnscap/commit/e4eb439cad1d8b7f133770793369f0457d88bf05, now the compile finishes fine.

**Comment by botovq** [comment]
> If I replace all the `#defines` in the `#if defined(__APPLE__) && !defined(HAVE_ENDIAN_H)` section of `include/compat/endian.h` with those from https://github.com/DNS-OARC/dnscap/commit/e4eb439cad1d8b7f133770793369f0457d88bf05, now the compile finishes fine.

Could you please make a PR with the change you're describing here? Your
description isn't clear enough to me and I made the changes to fix the
build with macOS in CI. This way we will see if what works for you also
works in CI.

**Comment by botovq** [comment]
> If I replace all the `#defines` in the `#if defined(__APPLE__) && !defined(HAVE_ENDIAN_H)` section of `include/compat/endian.h` with those from https://github.com/DNS-OARC/dnscap/commit/e4eb439cad1d8b7f133770793369f0457d88bf05, now the compile finishes fine.

The thing is, the macros in that section are the same apart from some
extra parentheses and the fact that we don't have le16 and le32 versions
which don't matter here. So you must have fixed your build by changing
something else.

Did you remove "&& !defined(HAVE_ENDIAN_H)"? Does that mean that you
have an endian.h somewhere in the include path?

**Comment by vollkommenheit** [comment]
> If I replace all the `#defines` in the `#if defined(__APPLE__) && !defined(HAVE_ENDIAN_H)` section of `include/compat/endian.h` with those from [DNS-OARC/dnscap@e4eb439](https://github.com/DNS-OARC/dnscap/commit/e4eb439cad1d8b7f133770793369f0457d88bf05), now the compile finishes fine.
> The thing is, the macros in that section are the same apart from some extra parentheses and the fact that we don't have le16 and le32 versions which don't matter here. So you must have fixed your build by changing something else. Did you remove "&& !defined(HAVE_ENDIAN_H)"? Does that mean that you have an endian.h somewhere in the include path?

Nah, I only replaced all the `#define` bits enclosed within #if defined(__APPLE__) && !defined(HAVE_ENDIAN_H)`. In other words, I leave the `&& !defined(HAVE_ENDIAN_H)` intact. 

However, before I created this issue, I did notice what you pointed out, that the `#define` stuff are basically identical, for the purpose of this issue. I can't explain why the `dnscap` snippet worked for me. I'm re-testing and closing this issue now.
