### ISSUE TITLE
libressl accepts a certificate containing two subject keys

### ISSUE THREAD

**Issue by llllmllll** [libressl/portable#869]
When I used libressl for digital certificate validation, I found that libressl validated a certificate with two subject key fields.This violates rfc5280 which states that a certificate "may not contain multiple instances of a particular extension".
The command I use is：`openssl verify -CAfile root.pem leaf.pem`
[leaf.txt](https://github.com/libressl/portable/files/11706698/leaf.txt)
[root.txt](https://github.com/libressl/portable/files/11706699/root.txt)

**Comment by 4a6f656c** [comment]
This is not reproducible here:
```
$ openssl version
LibreSSL 3.8.1
$ openssl verify -CAfile root.txt leaf.txt
C = CN, ST = TJ5, L = TJ, O = TJU, OU = beiyangyuan, CN = LQL, emailAddress = ljfpower@163.com
error 20 at 0 depth lookup:unable to get local issuer certificate
leaf.txt: verification failed: 20 (unable to get local issuer certificate)
```

**Comment by botovq** [comment]
Should be fixed in https://github.com/libressl/openbsd/commit/8d08c8768f2bf4f3b917ab04b87538ec387a36cb
