### ISSUE TITLE
PkeyUtl crashes with "Expecting: ANY PRIVATE KEY" in Mac OS

### ISSUE THREAD

**Issue by johnnywiller** [libressl/portable#870]
Hi, when running with `LibreSSL 3.7.3` in Mac OS, I get a crash like:
`> echo test | openssl pkeyutl -encrypt -inkey repository_key.pub.pem -pubin -out >(base64)`
```
unable to load Private Key
8519360000:error:09FFF06C:PEM routines:CRYPTO_internal:no start line:pem/pem_lib.c:694:Expecting: ANY PRIVATE KEY
Error initializing context
```
The same does not happen with `OpenSSL 3.1.1 30 May 2023`

```
cat repository_key.pub.pem
-----BEGIN PUBLIC KEY-----
....................
-----END PUBLIC KEY-----
```

<img width="1719" alt="Screenshot 2023-06-28 at 17 11 59" src="https://github.com/libressl/portable/assets/5539939/aa7af61e-c982-4312-84ed-abfda340379c">

It also works fine if using `rsautl` command

<img width="1723" alt="Screenshot 2023-06-28 at 17 27 55" src="https://github.com/libressl/portable/assets/5539939/abf5745d-72bc-42aa-8c9f-b3d7807575f3">

**Comment by botovq** [comment]
> Hi, when running with LibreSSL 3.7.3 in Mac OS, I get a crash like:

Your picture says 3.3.6.  It is not a crash but an error. What type of key is this?

**Comment by botovq** [comment]
This is not actionable without further info.
