### ISSUE TITLE
Self-modifying opensslconf.h during build not desirable

### ISSUE THREAD

**Issue by Steveice10** [libressl/portable#871]
I build libressl as a submodule of another project and would like the build process to not modify the tree, as it interferes with other checks for whether the source tree being built is dirty.

Since recently libressl has started modifying include/openssl/opensslconf.h as part of the build, overwriting it with an equivalent file from include/arch/(arch name)/opensslconf.h. It would be preferable for me if instead of overwriting the file, the build could just include the existing header from the arch path directly. That way the tree would stay clean.

**Comment by busterb** [comment]
Hmm, maybe this is possible if it's copied into the build tree instead of moving around the source tree. It's difficult to just leave it in-place since the internal #includes refer to it by openssl/openssl.conf everywhere (253 places)

**Comment by busterb** [comment]
Double-checking this, autoconf is doing the right thing and writing to the build directory. CMake is writing to the source directory. I'm assuming you're using CMake?

**Comment by Steveice10** [comment]
> Double-checking this, autoconf is doing the right thing and writing to the build directory. CMake is writing to the source directory. I'm assuming you're using CMake?

Correct, I'm using CMake.

**Comment by busterb** [comment]
Thanks, I merged the above fix and it should have the correct behavior now.
