### ISSUE TITLE
Failed to verify sums using GPG

### ISSUE THREAD

**Issue by tcely** [libressl/portable#904]
I was able to use signify to verify the SHA256 sums but the GPG signature isn't verified and the checksum for the `libressl.asc` file doesn't verify either.

The details about how I attempted this and the output is below:

```
bash $ curl -sSRLo sums-libressl.txt.asc 'https://ftp.openbsd.org/pub/OpenBSD/LibreSSL/SHA256.asc'
bash $ curl -sSRLo sums-libressl.txt.sig 'https://ftp.openbsd.org/pub/OpenBSD/LibreSSL/SHA256.sig'
bash $ curl -sSRLo libressl.pub 'https://ftp.openbsd.org/pub/OpenBSD/LibreSSL/libressl.pub'
bash $ curl -sSRLo libressl.asc 'https://ftp.openbsd.org/pub/OpenBSD/LibreSSL/libressl.asc'
bash $ printf -- '%s\n' "$(< libressl.pub)" 'RWT44PcJDPu8ZDd5GfXWW2vuE+xq4M3haXXfYohnEnWoEYCKHNFut6W8' | uniq -c
        1 untrusted comment: LibreSSL portable signify key, April 8 2020 public key
        2 RWT44PcJDPu8ZDd5GfXWW2vuE+xq4M3haXXfYohnEnWoEYCKHNFut6W8
bash $ printf 'signify: ' && signify -V -e -p libressl.pub -x sums-libressl.txt.sig -m sums-libressl.txt && \
> gpg --trust-model tofu+pgp --auto-key-import --auto-key-retrieve --keyid-format 0xlong --tofu-default-policy ask --verify sums-libressl.txt.asc sums-libressl.txt
signify: Signature Verified
gpg: Signature made 2023-05-27 08:44:40 -0400 EDT
gpg:                using RSA key 6F67522EC596C025B24549911FFAA0B24B708F96
gpg: BAD signature from "keybase.io/busterb <busterb@keybase.io>" [full]
bash $ grep -v -F libressl- sums-libressl.txt | cksum -c
libressl.asc: FAILED
libressl.pub: OK
cksum: WARNING: 1 computed checksum did NOT match
bash $ 
```

(Updated to embed the gist content.)

**Comment by busterb** [comment]
Thanks, verified that this GPG signature was for an earlier version of SHA256. It matches the one that was present earlier when libressl-3.7.2 was released.

$ tail sums-libressl.txt
SHA256 (libressl-3.6.2-relnotes.txt) = a280c86b7fd15185b6c75e0d3cfa59ea54ea50ed53e01a10e9ba3a6fdfbf7b1b
SHA256 (libressl-3.6.2.tar.gz) = 4be80fff073746cf50b4a8e5babe2795acae98c6b132a9e02519b445dfbfd033
SHA256 (libressl-3.7.0-relnotes.txt) = 8bc26fb61e44e66e1c76ae709a5e722f62a61b68014348774363732805bbd14a
SHA256 (libressl-3.7.0.tar.gz) = 3fc1290f4007ec75f6e9acecbb25512630d1b9ab8c53ba79844e395868c3e006
SHA256 (libressl-3.7.1-relnotes.txt) = 2e25f19273d5b5d089ecdc16638f868e2b33b29c4d103a8951c23b13e75e5acd
SHA256 (libressl-3.7.1.tar.gz) = 98086961a2b8b657ed0fea3056fb2db14294b6bfa193c15a5236a0a35c843ded
SHA256 (libressl-3.7.2-relnotes.txt) = d91f4bff58f6a804937d81df39f87da10cac7e416aadd2fb8556ffa28c92131e
SHA256 (libressl-3.7.2.tar.gz) = b06aa538fefc9c6b33c4db4931a09a5f52d9d2357219afcbff7d93fe12ebf6f7
SHA256 (libressl.asc) = c5c4e1351e949d4c77c77d25e3d431a8ff92118eb607ba4da35a4ed688ff028a
SHA256 (libressl.pub) = f70cba1370eb0ac5251f63fe9745b1efe4a6035054302dab4007e1fde1f34738

$ gpg --verify sums-libressl.txt.asc sums-libressl.txt
gpg: Signature made Sat 27 May 2023 07:44:40 AM CDT
gpg:                using RSA key 6F67522EC596C025B24549911FFAA0B24B708F96
gpg: Good signature from "keybase.io/busterb <busterb@keybase.io>" [ultimate]
gpg:                 aka "Brent Cook <busterb@gmail.com>" [ultimate]
gpg:                 aka "Brent Cook <bcook@openbsd.org>" [ultimate]
Primary key fingerprint: A1EB 079B 8D3E B92B 4EBD  3139 663A F51B D5E4 D8D5
     Subkey fingerprint: 6F67 522E C596 C025 B245  4991 1FFA A0B2 4B70 8F96

We'll update this with the next release, which should be shortly.
