### ISSUE TITLE
3.8.0, 3.8.1 Windows x86_64 ASM builds crashing on startup

### ISSUE THREAD

**Issue by vszakats** [libressl/portable#907]
ASM-enabled LibreSSL creates bad executables. They crash before even starting, as tested with `openssl.exe`.

ASM-enabled 3.7.3 builds run fine. Disabling ASM with 3.8.0, 3.8.1 fixes it.

The obvious difference between 3.7.3 and 3.8.0 ASM sources is the [addition](https://github.com/libressl/openbsd/commit/17bde8538e33793432c7952fdc0d5ddc780808e1) of `endbr64` instructions in 3.8.0. [ "Added endbr64 instructions to amd64 assembly." in ChangeLog. ]

OpenSSL [added support](https://github.com/openssl/openssl/commit/98ad3fe82bd3e7e7f929dd1fa4ef3915426002c0) for this in 2020, but it's not actually present in the x86_64 ASM sources generated for the MinGW target (haven't tested others), as seen in a recent 3.0.8 build.

This is the same issue as reported earlier as part of #893.

**Comment by busterb** [comment]
We'll get to this before the stable release.

**Comment by vszakats** [comment]
Thanks @busterb for working on this.

**Comment by busterb** [comment]
This should be fixed now as of #922, which will be in the 3.8.2 release. Thanks @vszakats

**Comment by vszakats** [comment]
Thank you @busterb, I can confirm this fixed.

**Comment by vszakats** [comment]
This issue returned with 3.8.3.

I'm building with CET enabled with mingw-w64. It worked fine with 3.8.2.
With 3.8.3, it's crashing the same way as 3.8.1 did.
