### ISSUE TITLE
Add ability to disable "overriding WinCrypt defines" warning

### ISSUE THREAD

**Issue by PabloMK7** [libressl/portable#919]
I'm using libressl in a huge project that has the flag "treat warnings as errors" enabled. Because of the `overriding WinCrypt defines` warning, it is not possible to compile the project.
For that reason, it would be beneficial to have a define so that warning is not generated if the user knows what they are doing.

```
#if defined(_WIN32) && defined(__WINCRYPT_H__)
#ifndef LIBRESSL_INTERNAL && !defined(LIBRESSL_DISABLE_OVERRIDE_WINCRYPT_DEFINES_WARNING)
#ifdef _MSC_VER
#pragma message("Warning, overriding WinCrypt defines")
#else
#warning overriding WinCrypt defines
#endif
#endif
```

**Comment by PabloMK7** [comment]
Sorry, upon further inspection I noticed I read the `#ifdef _MSC_VER` backwards as `#ifndef`. So it is actually possible to turn off the treat errors as warnings for user defined warnings in GCC. I'll keep the issue open to see if would still be beneficial to turn off that warning with a define.

**Comment by busterb** [comment]
Thanks for the updated @PabloMK7 . Let us know what you find out.

**Comment by PabloMK7** [comment]
> Thanks for the updated @PabloMK7 . Let us know what you find out.

Please ignore my second comment, I wasn't able to disable the warning in GCC either. We had to add a hacky workaround to not treat warnings as errors for libressl.

**Comment by botovq** [comment]
That's only about the three #warning in

https://github.com/libressl/portable/blob/master/patches/windows_headers.patch

right?

Could we not wrap them `#ifndef SILENT_WINCRYPT_OVERRIDES` or similar
to avoid this issue? Then compiling with `-DSILENT_WINCRYPT_OVERRIDES`
should fix your problem, no?

**Comment by busterb** [comment]
Sure, OK with adding the warning override.

**Comment by PabloMK7** [comment]
> Could we not wrap them `#ifndef SILENT_WINCRYPT_OVERRIDES` or similar to avoid this issue? Then compiling with `-DSILENT_WINCRYPT_OVERRIDES` should fix your problem, no?

This would indeed fix the issue. The linked PR will do it.
