### ISSUE TITLE
3.8.2 release?

### ISSUE THREAD

**Issue by daytime-brick** [libressl/portable#921]
https://github.com/sfackler/rust-openssl/issues/2050 is pending a release and missing newest version blocks a large number of crates which use openssl-sys

**Comment by busterb** [comment]
There are some platform fixes being tested in #922 that are important for the release. Thanks for your patience here.

**Comment by busterb** [comment]
Howdy, the 3.8.2 release is out now.
https://ftp.openbsd.org/pub/OpenBSD/LibreSSL/
