### ISSUE TITLE
3.8.2 unused variable 'savsig' [-Wunused-variable] on Windows

### ISSUE THREAD

**Issue by vszakats** [libressl/portable#925]
```
./libressl/crypto/ui/ui_openssl_win.c:134:15: warning: unused variable 'savsig' [-Wunused-variable]
  134 | static void (*savsig[NX509_SIG])(int );
      |               ^~~~~~
1 warning generated.
```

This variable appears unused, so this could be a fix:
```diff
--- a/ui_openssl_win.c	2023-11-03 15:08:28.468746666 +0000
+++ b/ui_openssl_win.c	2023-11-03 15:08:31.728355601 +0000
@@ -130,9 +130,6 @@
 #define NX509_SIG 32
 #endif
 
-/* Define globals.  They are protected by a lock */
-static void (*savsig[NX509_SIG])(int );
-
 DWORD console_mode;
 static FILE *tty_in, *tty_out;
 static int is_a_tty;
```

**Comment by botovq** [comment]
On Fri, Nov 03, 2023 at 08:10:28AM -0700, Viktor Szakats wrote:
> ```
> ./libressl/crypto/ui/ui_openssl_win.c:134:15: warning: unused variable 'savsig' [-Wunused-variable]
>   134 | static void (*savsig[NX509_SIG])(int );
>       |               ^~~~~~
> 1 warning generated.
> ```
> 
> This variable appears unused, so this could be a fix:
> ```diff
> --- ui_openssl_win-ORI.c	2023-11-03 15:08:28.468746666 +0000
> +++ ui_openssl_win.c	2023-11-03 15:08:31.728355601 +0000
> @@ -130,9 +130,6 @@
>  #define NX509_SIG 32
>  #endif
>  
> -/* Define globals.  They are protected by a lock */
> -static void (*savsig[NX509_SIG])(int );
> -
>  DWORD console_mode;
>  static FILE *tty_in, *tty_out;
>  static int is_a_tty;
> ```

Yes, that's correct. It's a leftover from

https://github.com/libressl/portable/commit/dd1d96f643b01a5edbe7e0db8399f3c88f5f0c8b
