### ISSUE TITLE
aes/aesni-macosx-x86_64.S:890:2: error: invalid instruction mnemonic 'endbr64'

### ISSUE THREAD

**Issue by vollkommenheit** [libressl/portable#933]
Same error as the resolved https://github.com/libressl/portable/issues/866 but now in another file:

> Making check in openssl
echo "generating opensslconf.h ..."
generating opensslconf.h ...
cp ../../include/arch/amd64/opensslconf.h opensslconf.h
/Applications/Xcode.app/Contents/Developer/usr/bin/make  check-am
make[3]: Nothing to be done for `check-am'.
make[2]: Nothing to be done for `check-am'.
Making check in crypto
echo "generating crypto_portable.sym ..."
generating crypto_portable.sym ...
cp ../crypto/crypto.sym crypto_portable.sym
chmod u+w crypto_portable.sym
/Applications/Xcode.app/Contents/Developer/usr/bin/make  check-am
  CPPAS    aes/libcrypto_la-aes-macosx-x86_64.lo
  CPPAS    aes/libcrypto_la-bsaes-macosx-x86_64.lo
  CPPAS    aes/libcrypto_la-vpaes-macosx-x86_64.lo
  CPPAS    aes/libcrypto_la-aesni-macosx-x86_64.lo
aes/aesni-macosx-x86_64.S:890:2: error: invalid instruction mnemonic 'endbr64'
 endbr64
 ^~~~~~~
make[2]: *** [aes/libcrypto_la-aesni-macosx-x86_64.lo] Error 1
make[1]: *** [check] Error 2
make: *** [check-recursive] Error 1
start make...
Making all in include
Making all in openssl
/Applications/Xcode.app/Contents/Developer/usr/bin/make  all-am
make[3]: Nothing to be done for `all-am'.
make[2]: Nothing to be done for `all-am'.
Making all in crypto
/Applications/Xcode.app/Contents/Developer/usr/bin/make  all-am
  CPPAS    aes/libcrypto_la-aesni-macosx-x86_64.lo
  CPPAS    aes/libcrypto_la-aesni-sha1-macosx-x86_64.lo
aes/aesni-macosx-x86_64.S:890:2: error: invalid instruction mnemonic 'endbr64'
 endbr64
 ^~~~~~~
make[2]: *** [aes/libcrypto_la-aesni-macosx-x86_64.lo] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [all] Error 2
make: *** [all-recursive] Error 1

Last successful build was 2023-10-21.

**Comment by busterb** [comment]
Can you tell us what version of macOS / xcode you're using please?

**Comment by vollkommenheit** [comment]
> Can you tell us what version of macOS / xcode you're using please?

clang -v
Apple LLVM version 8.0.0 (clang-800.0.42.1)
Target: x86_64-apple-darwin15.6.0
Thread model: posix

**Comment by armdn** [comment]
Same problem here...
Apple clang version 11.0.0 (clang-1100.0.33.17)
Target: x86_64-apple-darwin18.7.0
Thread model: posix

**Comment by busterb** [comment]
I'm assuming you're both using the release version of 3.8.2?

Hmm, will need to figure out how to make this fail in CI, which it isn't. Any thoughts @joshuasing ? We may need to adjust macos builds to be explicit about arch if they're not.

**Comment by busterb** [comment]
I see the issue, there was one missed patch in the aesni generator. It seems that the newer toolchains ignore this.

**Comment by vollkommenheit** [comment]
@busterb @botovq

**Comment by botovq** [comment]
On Wed, Nov 15, 2023 at 10:38:04PM -0800, vollkommenheit wrote:
> @busterb @botovq

It's expected. There was a patch in the first commit that should help you:

https://github.com/libressl/portable/pull/945/commits/d0d17f89eff5ddc331b9ef8cb517335efde56e9f

However, what I accidentally merged and then reverted was just a CI
change and apparently the CI still cannot reprdocue the problem you're
seeing.

**Comment by vollkommenheit** [comment]
> On Wed, Nov 15, 2023 at 10:38:04PM -0800, vollkommenheit wrote: @busterb @botovq
> It's expected. There was a patch in the first commit that should help you: [d0d17f8](https://github.com/libressl/portable/pull/945/commits/d0d17f89eff5ddc331b9ef8cb517335efde56e9f) However, what I accidentally merged and then reverted was just a CI change and apparently the CI still cannot reprdocue the problem you're seeing.

I'm not sure I follow. Do you mean https://github.com/libressl/portable/commit/d0d17f89eff5ddc331b9ef8cb517335efde56e9f was meant to deal with this https://github.com/libressl/portable/issues/933 issue, but the subsequent https://github.com/libressl/portable/commit/96e5e35d5eafa368d6ebfce4b48f66a5a3620e61 removing [patches/asm/0005-Revert-aesni-endbr64.patch](https://github.com/libressl/portable/commit/d0d17f89eff5ddc331b9ef8cb517335efde56e9f#diff-bf73944b0ce2b291930c6128343964a537d8101d83c62f61f9336a73fd369bc9) was deliberate?

>
commit 96e5e35d5eafa368d6ebfce4b48f66a5a3620e61
Author: Brent Cook <busterb@gmail.com>
Date:   Fri Nov 10 03:20:04 2023 -0600

    experiment forcing CI failure

commit d0d17f89eff5ddc331b9ef8cb517335efde56e9f
Author: Brent Cook <busterb@gmail.com>
Date:   Thu Nov 9 20:59:03 2023 -0600

    remove additional endbr64 patch, add tests for macos-11

**Comment by armdn** [comment]
With latest pulls on master now is everything goes smoothly. Builded just right now.
Apple clang version 11.0.0 (clang-1100.0.33.17)
Target: x86_64-apple-darwin18.7.0
Thread model: posix

**Comment by vollkommenheit** [comment]
> With latest pulls on master now is everything goes smoothly. Builded just right now. Apple clang version 11.0.0 (clang-1100.0.33.17) Target: x86_64-apple-darwin18.7.0 Thread model: posix

Thanks. Could you check if you have the ./patches/asm/0005-Revert-aesni-endbr64.patch in your build directory after pulling? I don't, which I guess is the problem on my end.

**Comment by armdn** [comment]
Yep, no such .patch file in this directory.

**Comment by botovq** [comment]
@vollkommenheit I have now landed patch 005 in #949. Hopefully that will resolve your issues if you build from HEAD.

**Comment by vollkommenheit** [comment]
>  CPPAS    sha/libcrypto_la-sha512-macosx-x86_64.lo
  CPPAS    whrlpool/libcrypto_la-wp-macosx-x86_64.lo
  CPPAS    libcrypto_la-cpuid-macosx-x86_64.lo
  CPPAS    bn/arch/amd64/libcrypto_la-bignum_add.lo
bn/arch/amd64/bignum_add.S:52:2: error: invalid instruction mnemonic 'endbr64'
 endbr64
 ^~~~~~~
make[2]: *** [bn/arch/amd64/libcrypto_la-bignum_add.lo] Error 1
make[1]: *** [check] Error 2
make: *** [check-recursive] Error 1

**Comment by busterb** [comment]
Mind posting the error in 3.8.3? I don't have an ancient machine to test on there, but it should have most of the fixes from 3.9.0.

**Comment by busterb** [comment]
Are you using a newer compiler than that OS shipped with? I tried it on an old vagrant box of 10.9 from 10 years ago, and while I had issues just using any of the basic tools like curl and wget, it seemed to build OK with the ancient stuff.

**Comment by busterb** [comment]
Thanks a lot @wtn
