### ISSUE TITLE
support `SSL_set0_wbio()` for parity with OpenSSL and forks

### ISSUE THREAD

**Issue by vszakats** [libressl/portable#939]
curl [started](https://github.com/curl/curl/commit/f39472ea9f4f4e12cfbc0500c4580a8d52ce4a59) [using](https://github.com/curl/curl/pull/10151) the OpenSSL function `SSL_set0_wbio()` in v7.88.0 (2023-02-15).

According to the commit message:
"for clear reference counting where available".

This function is available in OpenSSL/wolfSSL/BoringSSL/AWC-LC,
but not in LibreSSL (as of v3.8.2).

Would you be open to implement this in LibreSSL?

~~Untested patch~~ [deleted]

**Comment by botovq** [comment]
On Tue, Nov 07, 2023 at 04:24:02PM -0800, Viktor Szakats wrote:
> curl [started using](https://github.com/curl/curl/commit/f39472ea9f4f4e12cfbc0500c4580a8d52ce4a59) the OpenSSL function `SSL_set0_wbio()` in v7.88.0 (2023-02-15).
> 
> According to the ChangeLog:
> "for clear reference counting where available".

There is a reason this function is not available. As you saw, something
that looks like it is trivial to add, but the prerequisite for this to
be correct is a lot of hairy internal plumbing similar to things
explained in: https://boringssl-review.googlesource.com/8023

If you look at corresponding commits in OpenSSL you can see the many
things that went wrong along the way.

**Comment by vszakats** [comment]
Thanks for the pointer. Assuming these issues were ironed out 
in that patch, could that be applied to LibreSSL without having 
to go through that pain once again?

Just realized this is a duplicate of #838.

**Comment by vszakats** [comment]
One open Issue is enough for this, closing.
